CREATE TABLE CE_PRODUCT_CATEGORY
  (
    CATEGORY_SRCID NUMBER (8)        NOT NULL,
    CATEGORY_NAME  VARCHAR2 (100)     NOT NULL,
    CONSTRAINT "PK_CATEGORY_SRCID" PRIMARY KEY (CATEGORY_SRCID)
  );