

exec  FRAMEWORK.pkg_utl_drop.proc_drop_obj ('SEQ_DM_Payment_Type_ID', 'SEQUENCE');
exec  FRAMEWORK.pkg_utl_drop.proc_drop_obj ('SEQ_DM_Fuel_Type_ID', 'SEQUENCE');
exec  FRAMEWORK.pkg_utl_drop.proc_drop_obj ('SEQ_DM_Customer_ID', 'SEQUENCE');
exec  FRAMEWORK.pkg_utl_drop.proc_drop_obj ('SEQ_DM_AZS_ID', 'SEQUENCE');

CREATE SEQUENCE SEQ_DM_Payment_Type_ID 
	INCREMENT BY 1 
	START WITH 1 
	NOMAXVALUE 
	MINVALUE  1 
	NOCYCLE 
	NOCACHE 
	NOORDER
;
CREATE SEQUENCE SEQ_DM_Fuel_Type_ID 
	INCREMENT BY 1 
	START WITH 1 
	NOMAXVALUE 
	MINVALUE  1 
	NOCYCLE 
	NOCACHE 
	NOORDER
;
CREATE SEQUENCE SEQ_DM_Customer_ID 
	INCREMENT BY 1 
	START WITH 1 
	NOMAXVALUE 
	MINVALUE  1 
	NOCYCLE 
	NOCACHE 
	NOORDER
;
CREATE SEQUENCE SEQ_DM_AZS_ID 
	INCREMENT BY 1 
	START WITH 1 
	NOMAXVALUE 
	MINVALUE  1 
	NOCYCLE 
	NOCACHE 
	NOORDER
;


exec  FRAMEWORK.pkg_utl_drop.proc_drop_obj ('DIMAZS', 'TABLE');
exec  FRAMEWORK.pkg_utl_drop.proc_drop_obj ('DIMFUEL_TYPE', 'TABLE');
exec  FRAMEWORK.pkg_utl_drop.proc_drop_obj ('DIMPAYMENT_TYPE', 'TABLE');
exec  FRAMEWORK.pkg_utl_drop.proc_drop_obj ('DIMCUSTOMER', 'TABLE');
exec  FRAMEWORK.pkg_utl_drop.proc_drop_obj ('FCTPAYMENT', 'TABLE');



CREATE TABLE DIMAZS 
   (	AZS_SURR_ID NUMBER PRIMARY KEY, 
	ID3NF NUMBER(10,0), 
	NO NUMBER(4,0), 
	LOCATION_DESC VARCHAR2(255 BYTE), 
	LATITUDE NUMBER(10,6), 
	LONGITUDE VARCHAR2(26 BYTE), 
	ROAD1 VARCHAR2(26 BYTE), 
	ROAD2 VARCHAR2(5 BYTE), 
	DT NUMBER(1,0), 
	DT2 NUMBER(1,0), 
	AI92 NUMBER(1,0), 
	BN92 NUMBER(1,0), 
	AI95 NUMBER(1,0), 
	LPG NUMBER(1,0), 
	AI98 NUMBER(1,0), 
	ID_COUNTRY NUMBER(10,0), 
	COUNTRY_NAME VARCHAR2(100 BYTE), 
	COUNTRY_CODE VARCHAR2(100 BYTE), 
	ID_PARENT NUMBER(10,0), 
	ID_REGION NUMBER(10,0), 
	REGION_NAME VARCHAR2(100 BYTE), 
	ID_DISTRICT NUMBER(10,0), 
	DISTRICT_NAME VARCHAR2(100 BYTE), 
	UPDATE_DATE DATE, 
	INSERT_DATE DATE default sysdate
   );
   
CREATE TABLE DIMCUSTOMER 
   (	CUSTOMER_SURR_ID NUMBER PRIMARY KEY, 
	ID3NF NUMBER(10,0), 
	CUSTOMER_NK VARCHAR2(50 BYTE), 
	ID_CUSTOMER_TYPE NUMBER(1,0), 
	CUSTOMER_TYPE_DESCRIPTION VARCHAR2(50 BYTE), 
	ID_LOCATION NUMBER(10,0), 
	ADDRESS VARCHAR2(50 BYTE), 
	PHONE VARCHAR2(50 BYTE), 
	POSTALCODE NUMBER(8,0), 
	EMAIL VARCHAR2(50 BYTE), 
	FIRST_NAME VARCHAR2(50 BYTE), 
	LAST_NAME VARCHAR2(50 BYTE), 
	MIDDLE_NAME VARCHAR2(50 BYTE), 
	BIRTHDAY DATE, 
	SEX NUMBER, 
	VEHICLE_DESC VARCHAR2(50 BYTE), 
	VEHICLE_YEAR NUMBER, 
	TAX_ID VARCHAR2(50 BYTE), 
	RUS_FULL_NAME VARCHAR2(400 BYTE), 
	MNS_NAME VARCHAR2(128 BYTE), 
	MNS_NUM NUMBER, 
	UPDATE_DATE DATE, 
	INSERT_DATE DATE
   );
CREATE TABLE DIMFUEL_TYPE 
   (	FUEL_TYPE_SURR_ID NUMBER PRIMARY KEY, 
	ID3NF NUMBER(16,0), 
	ID_FUEL_CODE NUMBER(3,0), 
	ENG_TYPE VARCHAR2(10 BYTE), 
	RUS_TYPE VARCHAR2(26 BYTE), 
	DESCRIPTION VARCHAR2(128 BYTE), 
	START_DATE DATE, 
	END_DATE DATE, 
	IS_ACTIVE NUMBER, 
	INSERT_DATE DATE default sysdate
   );
CREATE TABLE DIMPAYMENT_TYPE 
   (	PAYMENT_TYPE_SURR_ID NUMBER PRIMARY KEY, 
	ID3NF NUMBER(16,0), 
	ID_PAYMENT_TYPE NUMBER(2,0), 
	ENG_TYPE VARCHAR2(10 BYTE), 
	RUS_TYPE VARCHAR2(100 BYTE), 
	DESCRIPTION VARCHAR2(128 BYTE), 
	START_DATE DATE, 
	END_DATE DATE, 
	IS_ACTIVE NUMBER, 
	INSERT_DATE DATE default sysdate
   );
CREATE TABLE FCTPAYMENT 
   (	ID_PAYMENT NUMBER, 
	ID_CUSTOMER NUMBER, 
	ID_PAYMENT_TYPE NUMBER, 
	ID_STATION NUMBER, 
	ID_FUEL_TYPE NUMBER, 
	PAYMENT_DATE DATE, 
	PRICE NUMBER(8,2), 
	QUANTITY NUMBER(10,3), 
	PAYMENT_TIME VARCHAR2(10 BYTE), 
	INSERT_DATE DATE default sysdate,
	CONSTRAINT FK_FCTPAYMENT_DIMAZS FOREIGN KEY (ID_STATION)
	  REFERENCES DIMAZS (AZS_SURR_ID) ENABLE,
  CONSTRAINT FK_FCTPAYMENT_DIMCUSTOMER FOREIGN KEY (ID_CUSTOMER)
	  REFERENCES DIMCUSTOMER (CUSTOMER_SURR_ID) ENABLE,
  CONSTRAINT FK_FCTPAYMENT_DIMFUEL_TYPE FOREIGN KEY (ID_FUEL_TYPE)
	  REFERENCES DIMFUEL_TYPE (FUEL_TYPE_SURR_ID) ENABLE,
  CONSTRAINT FK_FCTPAYMENT_DIMPAYMENT_TYPE FOREIGN KEY (ID_PAYMENT_TYPE)
	  REFERENCES DIMPAYMENT_TYPE (PAYMENT_TYPE_SURR_ID) ENABLE
  )PARTITION BY RANGE (PAYMENT_DATE)
  (
  PARTITION pr0 VALUES LESS THAN (TO_DATE('01-01-2016', 'DD-MM-YYYY')),
  PARTITION pr1 VALUES LESS THAN (TO_DATE('01-01-2017', 'DD-MM-YYYY')),
  PARTITION pr2 VALUES LESS THAN (TO_DATE('01-01-2018', 'DD-MM-YYYY')),
  PARTITION pr3 VALUES LESS THAN (TO_DATE('01-01-2019', 'DD-MM-YYYY')),
  PARTITION pr4 VALUES LESS THAN (MAXVALUE)
  );
   alter TABLE FCTPAYMENT add
   CONSTRAINT FK_FCTPAYMENT_DIMDATE FOREIGN KEY (PAYMENT_DATE)
	  REFERENCES DIMDATE (DATE_ID) ENABLE;

  /*ALTER TABLE DIMAZS MODIFY (ID3NF NOT NULL ENABLE);
  ALTER TABLE DIMAZS MODIFY (NO NOT NULL ENABLE);
  ALTER TABLE DIMAZS MODIFY (LOCATION_DESC NOT NULL ENABLE);
  ALTER TABLE DIMAZS MODIFY (LATITUDE NOT NULL ENABLE);
  ALTER TABLE DIMAZS MODIFY (LONGITUDE NOT NULL ENABLE);
  ALTER TABLE DIMAZS MODIFY (ROAD1 NOT NULL ENABLE);
  ALTER TABLE DIMAZS MODIFY (ROAD2 NOT NULL ENABLE);
  ALTER TABLE DIMAZS MODIFY (DT NOT NULL ENABLE);
  ALTER TABLE DIMAZS MODIFY (DT2 NOT NULL ENABLE);
  ALTER TABLE DIMAZS MODIFY (AI92 NOT NULL ENABLE);
  ALTER TABLE DIMAZS MODIFY (BN92 NOT NULL ENABLE);
  ALTER TABLE DIMAZS MODIFY (AI95 NOT NULL ENABLE);
  ALTER TABLE DIMAZS MODIFY (LPG NOT NULL ENABLE);
  ALTER TABLE DIMAZS MODIFY (AI98 NOT NULL ENABLE);
  ALTER TABLE DIMAZS MODIFY (ID_COUNTRY NOT NULL ENABLE);
  ALTER TABLE DIMAZS MODIFY (COUNTRY_NAME NOT NULL ENABLE);
  ALTER TABLE DIMAZS MODIFY (COUNTRY_CODE NOT NULL ENABLE);
  ALTER TABLE DIMAZS MODIFY (ID_PARENT NOT NULL ENABLE);
  ALTER TABLE DIMAZS MODIFY (ID_REGION NOT NULL ENABLE);
  ALTER TABLE DIMAZS MODIFY (REGION_NAME NOT NULL ENABLE);
  ALTER TABLE DIMAZS MODIFY (ID_DISTRICT NOT NULL ENABLE);
  ALTER TABLE DIMAZS MODIFY (DISTRICT_NAME NOT NULL ENABLE);
  ALTER TABLE DIMAZS MODIFY (UPDATE_DATE NOT NULL ENABLE);
  ALTER TABLE DIMAZS MODIFY (INSERT_DATE NOT NULL ENABLE);
--  ALTER TABLE DIMAZS ADD PRIMARY KEY (AZS_SURR_ID);

--  Constraints for Table DIMCUSTOMER
  ALTER TABLE DIMCUSTOMER MODIFY (ID3NF NOT NULL ENABLE);
  ALTER TABLE DIMCUSTOMER MODIFY (CUSTOMER_NK NOT NULL ENABLE);
  ALTER TABLE DIMCUSTOMER MODIFY (ID_CUSTOMER_TYPE NOT NULL ENABLE);
  ALTER TABLE DIMCUSTOMER MODIFY (CUSTOMER_TYPE_DESCRIPTION NOT NULL ENABLE);
  ALTER TABLE DIMCUSTOMER MODIFY (ID_LOCATION NOT NULL ENABLE);
  ALTER TABLE DIMCUSTOMER MODIFY (ADDRESS NOT NULL ENABLE);
  ALTER TABLE DIMCUSTOMER MODIFY (PHONE NOT NULL ENABLE);
  ALTER TABLE DIMCUSTOMER MODIFY (POSTALCODE NOT NULL ENABLE);
  ALTER TABLE DIMCUSTOMER MODIFY (EMAIL NOT NULL ENABLE);
  ALTER TABLE DIMCUSTOMER MODIFY (FIRST_NAME NOT NULL ENABLE);
  ALTER TABLE DIMCUSTOMER MODIFY (LAST_NAME NOT NULL ENABLE);
  ALTER TABLE DIMCUSTOMER MODIFY (MIDDLE_NAME NOT NULL ENABLE);
  ALTER TABLE DIMCUSTOMER MODIFY (VEHICLE_DESC NOT NULL ENABLE);
  ALTER TABLE DIMCUSTOMER MODIFY (TAX_ID NOT NULL ENABLE);
  ALTER TABLE DIMCUSTOMER MODIFY (RUS_FULL_NAME NOT NULL ENABLE);
  ALTER TABLE DIMCUSTOMER MODIFY (MNS_NAME NOT NULL ENABLE);
  ALTER TABLE DIMCUSTOMER MODIFY (UPDATE_DATE NOT NULL ENABLE);
  ALTER TABLE DIMCUSTOMER MODIFY (INSERT_DATE NOT NULL ENABLE);
 -- ALTER TABLE DIMCUSTOMER ADD PRIMARY KEY (CUSTOMER_SURR_ID);


--  Constraints for Table DIMFUEL_TYPE
  ALTER TABLE DIMFUEL_TYPE MODIFY (ID3NF NOT NULL ENABLE);
  ALTER TABLE DIMFUEL_TYPE MODIFY (ID_FUEL_CODE NOT NULL ENABLE);
  ALTER TABLE DIMFUEL_TYPE MODIFY (ENG_TYPE NOT NULL ENABLE);
  ALTER TABLE DIMFUEL_TYPE MODIFY (RUS_TYPE NOT NULL ENABLE);
  ALTER TABLE DIMFUEL_TYPE MODIFY (DESCRIPTION NOT NULL ENABLE);
  ALTER TABLE DIMFUEL_TYPE MODIFY (START_DATE NOT NULL ENABLE);
  ALTER TABLE DIMFUEL_TYPE MODIFY (END_DATE NOT NULL ENABLE);
  ALTER TABLE DIMFUEL_TYPE MODIFY (INSERT_DATE NOT NULL ENABLE);
--  ALTER TABLE DIMFUEL_TYPE ADD PRIMARY KEY (FUEL_TYPE_SURR_ID);


-- Constraints for Table DIMPAYMENT_TYPE

  ALTER TABLE DIMPAYMENT_TYPE MODIFY (ID3NF NOT NULL ENABLE);
  ALTER TABLE DIMPAYMENT_TYPE MODIFY (ID_PAYMENT_TYPE NOT NULL ENABLE);
  ALTER TABLE DIMPAYMENT_TYPE MODIFY (ENG_TYPE NOT NULL ENABLE);
  ALTER TABLE DIMPAYMENT_TYPE MODIFY (RUS_TYPE NOT NULL ENABLE);
  ALTER TABLE DIMPAYMENT_TYPE MODIFY (DESCRIPTION NOT NULL ENABLE);
  ALTER TABLE DIMPAYMENT_TYPE MODIFY (START_DATE NOT NULL ENABLE);
  ALTER TABLE DIMPAYMENT_TYPE MODIFY (END_DATE NOT NULL ENABLE);
  ALTER TABLE DIMPAYMENT_TYPE MODIFY (INSERT_DATE NOT NULL ENABLE);
--  ALTER TABLE DIMPAYMENT_TYPE ADD PRIMARY KEY (PAYMENT_TYPE_SURR_ID);
  
/*  Constraints for Table FCTPAYMENT*/
  ALTER TABLE FCTPAYMENT MODIFY (ID_PAYMENT NOT NULL ENABLE);
  ALTER TABLE FCTPAYMENT MODIFY (ID_CUSTOMER NOT NULL ENABLE);
  ALTER TABLE FCTPAYMENT MODIFY (ID_PAYMENT_TYPE NOT NULL ENABLE);
  ALTER TABLE FCTPAYMENT MODIFY (ID_STATION NOT NULL ENABLE);
  ALTER TABLE FCTPAYMENT MODIFY (ID_FUEL_TYPE NOT NULL ENABLE);
  ALTER TABLE FCTPAYMENT MODIFY (PAYMENT_DATE NOT NULL ENABLE);
  ALTER TABLE FCTPAYMENT MODIFY (PRICE NOT NULL ENABLE);
  ALTER TABLE FCTPAYMENT MODIFY (QUANTITY NOT NULL ENABLE);
  ALTER TABLE FCTPAYMENT MODIFY (PAYMENT_TIME NOT NULL ENABLE);
  ALTER TABLE FCTPAYMENT MODIFY (INSERT_DATE NOT NULL ENABLE);



exec FRAMEWORK.pkg_utl_grants_mgmt.proc_grant (' SELECT', 'BL_DM','SEQ_DM_Payment_Type_ID','FRAMEWORK');
exec FRAMEWORK.pkg_utl_grants_mgmt.proc_grant (' SELECT', 'BL_DM','SEQ_DM_Fuel_Type_ID','FRAMEWORK');
exec FRAMEWORK.pkg_utl_grants_mgmt.proc_grant (' SELECT', 'BL_DM','SEQ_DM_Customer_ID','FRAMEWORK');
exec FRAMEWORK.pkg_utl_grants_mgmt.proc_grant (' SELECT', 'BL_DM','SEQ_DM_AZS_ID','FRAMEWORK');

exec FRAMEWORK.pkg_utl_grants_mgmt.proc_grant (' SELECT, INSERT, UPDATE, DELETE', 'BL_DM','DIMAZS','BL_CL_DM');
exec FRAMEWORK.pkg_utl_grants_mgmt.proc_grant (' SELECT, INSERT, UPDATE, DELETE', 'BL_DM','DIMFUEL_TYPE','BL_CL_DM');
exec FRAMEWORK.pkg_utl_grants_mgmt.proc_grant (' SELECT, INSERT, UPDATE, DELETE', 'BL_DM','DIMPAYMENT_TYPE','BL_CL_DM');
exec FRAMEWORK.pkg_utl_grants_mgmt.proc_grant (' SELECT, INSERT, UPDATE, DELETE', 'BL_DM','DIMDATE','BL_CL_DM');
exec FRAMEWORK.pkg_utl_grants_mgmt.proc_grant (' SELECT, INSERT, UPDATE, DELETE', 'BL_DM','DIMCUSTOMER','BL_CL_DM');
exec FRAMEWORK.pkg_utl_grants_mgmt.proc_grant (' SELECT, INSERT, UPDATE, DELETE', 'BL_DM','FCTPAYMENT','BL_CL_DM');

exec FRAMEWORK.pkg_utl_grants_mgmt.proc_grant (' SELECT', 'BL_DM','DIMAZS','FRAMEWORK');
exec FRAMEWORK.pkg_utl_grants_mgmt.proc_grant (' SELECT', 'BL_DM','DIMFUEL_TYPE','FRAMEWORK');
exec FRAMEWORK.pkg_utl_grants_mgmt.proc_grant (' SELECT', 'BL_DM','DIMPAYMENT_TYPE','FRAMEWORK');
exec FRAMEWORK.pkg_utl_grants_mgmt.proc_grant (' SELECT', 'BL_DM','DIMDATE','FRAMEWORK');
exec FRAMEWORK.pkg_utl_grants_mgmt.proc_grant (' SELECT', 'BL_DM','DIMCUSTOMER','FRAMEWORK');
exec FRAMEWORK.pkg_utl_grants_mgmt.proc_grant (' SELECT', 'BL_DM','FCTPAYMENT','FRAMEWORK');

  
