CREATE TABLE CLS_EMPLOYEES
(
	"EMPLOYEE_ID" NUMBER(8) NOT NULL,
	"LAST_NAME" VARCHAR2(50),
	"FIRST_NAME" VARCHAR2(50),
	"MIDDLE_NAME" VARCHAR2(50),
	"ADDRESS_ID" NUMBER(8) NOT NULL,
	"EMAIL" VARCHAR2(50),
	"PHONE" VARCHAR2(50),
	"MANAGER_ID" NUMBER(4) NOT NULL,
	"STORE_ID" NUMBER(4) NOT NULL
)
;