CREATE TABLE CLS_PRODUCTS
(
	"PRODUCT_ID" NUMBER(8) NOT NULL,
	"PROVIDER_ID" NUMBER(8) NOT NULL,
	"SUBCATEGORY_ID" NUMBER(8) NOT NULL,
	"MANUFACTURER_COUNTRY" VARCHAR2(50),
	"START_DT" DATE NOT NULL,
	"END_DT" DATE NOT NULL,
	"IS_CURRENT" VARCHAR2(10) NOT NULL,
	"SUB_CATEGORY_ID" NUMBER
)
;