CREATE TABLE CLS_SALES
(
	"SALE_ID" NUMBER(8) NOT NULL,
	"SALE_DATE" DATE,
	"PRODUCT_ID" NUMBER(8) NOT NULL,
	"STORE_ID" NUMBER(8) NOT NULL,
	"CUSTOMER_ID" NUMBER(8) NOT NULL,
	"AMOUNT_SOLD_ITEMS" NUMBER(8),
	"TOTAL_COST" NUMBER(8),
	"EMPLOYEE_ID" NUMBER(8) NOT NULL
)
;