CREATE TABLE CLS_CUSTOMERS
(
	"CUSTOMER_ID" NUMBER(8) NOT NULL,
	"CUSTOMER_CODE" NUMBER(4),
	"LAST_NAME" VARCHAR2(50),
	"FIRST_NAME" VARCHAR2(50),
	"MIDDLE_NAME" VARCHAR2(50),
	"ADDRESS_ID" NUMBER(8),
	"EMAIL" VARCHAR2(50),
	"PHONE" VARCHAR2(50),
	"AGE_CATEGORY_ID" NUMBER(2),
	"START_DT" DATE,
	"END_DT" DATE,
	"IS_CURRENT" VARCHAR2(10)
)
;