ALTER TABLE CLS_STORES 
 ADD CONSTRAINT "PK_STORES"
	PRIMARY KEY ("STORE_ID") USING INDEX
;

ALTER TABLE CLS_SALES 
 ADD CONSTRAINT "PK_SALES"
	PRIMARY KEY ("SALE_ID") USING INDEX
;

ALTER TABLE CLS_REGIONS 
 ADD CONSTRAINT "PK_REGIONS"
	PRIMARY KEY ("REGION_ID") USING INDEX
;

ALTER TABLE CLS_PROVIDERS 
 ADD CONSTRAINT "PK_PROVIDERS"
	PRIMARY KEY ("PROVIDER_ID") USING INDEX
;

ALTER TABLE CLS_PRODUCTS 
 ADD CONSTRAINT "PK_PRODUCTS"
	PRIMARY KEY ("PRODUCT_ID") USING INDEX
;

ALTER TABLE CLS_PRODUCT_SUBCATEGORIES 
 ADD CONSTRAINT "PK_PRODUCT_SUBC_01"
	PRIMARY KEY ("SUB_CATEGORY_ID") USING INDEX
;

ALTER TABLE CLS_PRODUCT_CATEGORIES 
 ADD CONSTRAINT "PK_PRODUCT_CATEG_01"
	PRIMARY KEY ("CATEGORY_ID") USING INDEX
;

ALTER TABLE CLS_EMPLOYEES 
 ADD CONSTRAINT "PK_EMPLOYEES"
	PRIMARY KEY ("MANAGER_ID","EMPLOYEE_ID") USING INDEX
;

ALTER TABLE CLS_CUSTOMERS 
 ADD CONSTRAINT "PK_CUSTOMERS"
	PRIMARY KEY ("CUSTOMER_ID") USING INDEX
;

ALTER TABLE CLS_COUNTRIES 
 ADD CONSTRAINT "PK_COUNTRIES"
	PRIMARY KEY ("COUNTRY_ID") USING INDEX
;

ALTER TABLE CLS_CITIES 
 ADD CONSTRAINT "PK_CITIES"
	PRIMARY KEY ("CITY_ID") USING INDEX
;

ALTER TABLE CLS_AGE_CATEGORIES 
 ADD CONSTRAINT "PK_AGE_CATEGORI_01"
	PRIMARY KEY ("AGE_CATEGORY_ID") USING INDEX
;

ALTER TABLE CLS_ADDRESSES 
 ADD CONSTRAINT "PK_ADDRESSES"
	PRIMARY KEY ("ADDRESS_ID") USING INDEX
;

ALTER TABLE CLS_STORES 
 ADD CONSTRAINT "FK_STORES_ADDRESSES"
	FOREIGN KEY ("ADDRESS_ID") REFERENCES CLS_ADDRESSES ("ADDRESS_ID")
;

ALTER TABLE CLS_SALES 
 ADD CONSTRAINT "FK_SALES_CUSTOMERS"
	FOREIGN KEY ("CUSTOMER_ID") REFERENCES CLS_CUSTOMERS ("CUSTOMER_ID")
;

ALTER TABLE CLS_SALES 
 ADD CONSTRAINT "FK_SALES_PRODUCTS"
	FOREIGN KEY ("PRODUCT_ID") REFERENCES CLS_PRODUCTS ("PRODUCT_ID")
;

ALTER TABLE CLS_SALES 
 ADD CONSTRAINT "FK_SALES_STORES"
	FOREIGN KEY ("STORE_ID") REFERENCES CLS_STORES ("STORE_ID")
;

ALTER TABLE CLS_PROVIDERS 
 ADD CONSTRAINT "FK_PROVIDERS_ADDRESSES"
	FOREIGN KEY ("ADDRESS_ID") REFERENCES CLS_ADDRESSES ("ADDRESS_ID")
;

ALTER TABLE CLS_PRODUCTS 
 ADD CONSTRAINT "FK_PRODUCTS_PRODUCT_SUBCATE_01"
	FOREIGN KEY ("SUB_CATEGORY_ID") REFERENCES CLS_PRODUCT_SUBCATEGORIES ("SUB_CATEGORY_ID")
;

ALTER TABLE CLS_PRODUCTS 
 ADD CONSTRAINT "FK_PRODUCTS_PROVIDERS"
	FOREIGN KEY ("PROVIDER_ID") REFERENCES CLS_PROVIDERS ("PROVIDER_ID")
;

ALTER TABLE CLS_PRODUCT_SUBCATEGORIES 
 ADD CONSTRAINT "FK_PRODUCT_SUBC_PRODUCT_CAT_01"
	FOREIGN KEY ("CATEGORY_ID") REFERENCES CLS_PRODUCT_CATEGORIES ("CATEGORY_ID")
;

ALTER TABLE CLS_EMPLOYEES
 ADD CONSTRAINT "FK_EMPLOYEES_ADDRESSES"
	FOREIGN KEY ("ADDRESS_ID") REFERENCES CLS_ADDRESSES ("ADDRESS_ID")
;

ALTER TABLE CLS_EMPLOYEES 
 ADD CONSTRAINT "FK_EMPLOYEES_EMPLOYEES"
	FOREIGN KEY ("MANAGER_ID","EMPLOYEE_ID") REFERENCES CLS_EMPLOYEES ("MANAGER_ID","EMPLOYEE_ID")
;

ALTER TABLE CLS_EMPLOYEES 
 ADD CONSTRAINT "FK_EMPLOYEES_STORES"
	FOREIGN KEY ("STORE_ID") REFERENCES CLS_STORES ("STORE_ID")
;

ALTER TABLE CLS_CUSTOMERS 
 ADD CONSTRAINT "FK_CUSTOMERS_ADDRESSES"
	FOREIGN KEY ("ADDRESS_ID") REFERENCES CLS_ADDRESSES ("ADDRESS_ID")
;

ALTER TABLE CLS_CUSTOMERS 
 ADD CONSTRAINT "FK_CUSTOMERS_AGE_CATEGORIES"
	FOREIGN KEY ("AGE_CATEGORY_ID") REFERENCES CLS_AGE_CATEGORIES ("AGE_CATEGORY_ID")
;

ALTER TABLE CLS_COUNTRIES 
 ADD CONSTRAINT "FK_COUNTRIES_REGIONS"
	FOREIGN KEY ("REGION_ID") REFERENCES CLS_REGIONS ("REGION_ID")
;

ALTER TABLE CLS_CITIES 
 ADD CONSTRAINT "FK_CITIES_COUNTRIES"
	FOREIGN KEY ("COUNTRY_ID") REFERENCES CLS_COUNTRIES ("COUNTRY_ID")
;

ALTER TABLE CLS_ADDRESSES 
 ADD CONSTRAINT "FK_ADDRESSES_CITIES"
	FOREIGN KEY ("CITY_ID") REFERENCES CLS_CITIES ("CITY_ID")
;
