CREATE OR REPLACE PACKAGE BODY PKG_ETL_INSERT_ADDRESS
AS
  PROCEDURE INSERT_TABLE_ADDRESS
    IS
    BEGIN 
    EXECUTE IMMEDIATE ('TRUNCATE TABLE CLS_ADDRESS');
    INSERT INTO CLS_ADDRESS(ADDRESS,POSTAL_CODE,CITY) 
        SELECT * FROM (SELECT streetaddress,zipcode,city 
    FROM WRK_customers
UNION 
SELECT streetaddress,zipcode,city 
    FROM WRK_suppliers);
    COMMIT;
    EXCEPTION WHEN OTHERS THEN RAISE;
  END INSERT_TABLE_ADDRESS;
---  
  PROCEDURE MERGE_TABLE_ADDRESS
  IS 
  BEGIN 
  MERGE INTO bl_3nf.ce_ADDRESS NFAD USING
    (SELECT 
     ADDRESS_SRCID,
      ADDRESS,
      POSTAL_CODE,
      C.CITY_SRCID
        FROM CLS_ADDRESS, BL_3NF.CE_CITY C
        WHERE CLS_ADDRESS.CITY = C.CITY 
    MINUS
     SELECT 
     ADDRESS_SRCID,
     ADDRESS,
     POSTAL_CODE,
      CITY_SRCID
    FROM bl_3nf.ce_ADDRESS
    ) CLSAD ON (CLSAD.CITY_SRCID =NFAD.CITY_SRCID)
  WHEN MATCHED THEN 
    UPDATE SET NFAD.ADDRESS = CLSAD.ADDRESS
  WHEN NOT MATCHED THEN
    INSERT 
      (
        ADDRESS_SRCID,
        ADDRESS,
        POSTAL_CODE,
        CITY_SRCID 
      )
    VALUES
      (
        bl_3nf.ADDRESS_SEQ.NEXTVAL,
        CLSAD.ADDRESS,
        CLSAD.POSTAL_CODE,
        CLSAD.CITY_SRCID
      );
    COMMIT;
  EXCEPTION 
    WHEN OTHERS THEN RAISE ;
  END MERGE_TABLE_ADDRESS;
END PKG_ETL_INSERT_ADDRESS;
/