CREATE TABLE DimDate
  (
    FULL_DATE_DT                DATE NOT NULL,
    FULL_DATE_DESCR             VARCHAR2(20) NOT NULL,
    DAY_OF_WEEK                 NUMBER(1) NOT NULL,
    DAY_OF_MONTH                NUMBER(2) NOT NULL,
    DAY_OF_YEAR                 NUMBER(3) NOT NULL,
    DAY_NAME                    VARCHAR2(10) NOT NULL,
    WEEKEND_INDICATOR           VARCHAR2(40) NOT NULL,
    LAST_DAY_OF_WEEK_INDICATOR  VARCHAR2(40) NOT NULL,
    LAST_DAY_OF_MONTH_INDICATOR VARCHAR2(40) NOT NULL,
    WEEK_OF_MONTH               NUMBER(1) NOT NULL,
    WEEK_OF_YEAR                NUMBER(2) NOT NULL,
    WEEK_ENDING_DT              DATE NOT NULL,
    MONTH_NUMBER                NUMBER(2) NOT NULL,
    MONTH_NAME                  VARCHAR2(30) NOT NULL,
    MONTH_YEAR                  VARCHAR2(30) NOT NULL,
    QUARTER_NUMBER              NUMBER(3) NOT NULL,
    QUARTER_YEAR                CHAR(30) NOT NULL,
    YEAR_NUMBER                 NUMBER(4) NOT NULL,
    CONSTRAINT DATE_DIMENSION_PK PRIMARY KEY (FULL_DATE_DT)
  );
