-- CREATE TABLESPACE. 
CREATE TABLESPACE tbs_pdb_bl_3nf DATAFILE
    'TBS_PDB_001.DBF' SIZE 104857600
        AUTOEXTEND ON NEXT 20971520
NOLOGGING SEGMENT SPACE MANAGEMENT AUTO EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

-- CREATE USER.
CREATE USER bl_3nf 
IDENTIFIED BY "12345" 
DEFAULT TABLESPACE tbs_pdb_bl_3nf;

--GRANTS
GRANT CONNECT to bl_3nf;
GRANT RESOURCE to bl_3nf;
GRANT DBA to bl_3nf;
