CREATE OR REPLACE PACKAGE BODY PKG_ETL_INSERT_CITY
AS
  PROCEDURE INSERT_TABLE_CITY
    IS
    BEGIN 
    EXECUTE IMMEDIATE ('TRUNCATE TABLE CLS_CITY');
    INSERT INTO CLS_CITY(CITY,ATE_NAME) 
       SELECT * FROM (SELECT distinct(nvl(CITY,'-99')),NVL(STATEFULL,'-99') 
    FROM WRK_CUSTOMERS 
UNION 
SELECT distinct(nvl(CITY,'-99')),NVL(STATEFULL,'-99')
    FROM WRK_SUPPLIERS);
    COMMIT;
    EXCEPTION WHEN OTHERS THEN RAISE;
  END INSERT_TABLE_CITY;
---  
  PROCEDURE MERGE_TABLE_CITY
  IS 
  BEGIN 
  MERGE INTO bl_3nf.ce_CITY NFC USING
    (SELECT 
     CITY_SRCID,
      CITY,
      A.ATE_SRCID
        FROM CLS_CITY, BL_3NF.CE_ATE A
        WHERE CLS_CITY.ATE_NAME = A.ATE_NAME 
    MINUS
     SELECT 
     CITY_SRCID,
      CITY,
      ATE_SRCID
    FROM bl_3nf.ce_CITY
    ) CLSC ON (CLSC.ATE_SRCID =NFC.ATE_SRCID)
  WHEN MATCHED THEN 
    UPDATE SET NFC.CITY = CLSC.CITY
  WHEN NOT MATCHED THEN
    INSERT 
      (
        CITY_SRCID,
        CITY,
        ATE_SRCID 
      )
    VALUES
      (
        bl_3nf.CITY_SEQ.NEXTVAL,
        CLSC.CITY,
        CLSC.ATE_SRCID
      );
    COMMIT;
  EXCEPTION 
    WHEN OTHERS THEN RAISE ;
  END MERGE_TABLE_CITY;
END PKG_ETL_INSERT_CITY;
/