-- Grants to bl_cl2
GRANT CREATE ANY SYNONYM TO bl_cl2;
GRANT CREATE ANY PROCEDURE TO bl_cl2;
GRANT SELECT ON sa_src.ext_products TO bl_cl2;
GRANT SELECT ON sa_src.ext_consumers TO bl_cl2;
GRANT SELECT ON sa_src.ext_departments TO bl_cl2;
GRANT SELECT ON "BL_3NF"."CE_COUNTRIES" TO bl_cl2;
GRANT SELECT ON "BL_3NF"."CE_SALES" TO bl_cl2;
GRANT SELECT ON "BL_3NF"."CE_RESPONSIBLE" TO bl_cl2;
GRANT SELECT ON "BL_3NF"."CE_REGIONS" TO bl_cl2;
GRANT SELECT ON "BL_3NF"."CE_PROMOTIONS" TO bl_cl2;
GRANT SELECT ON "BL_3NF"."CE_PRODUCTS" TO bl_cl2;
GRANT SELECT ON "BL_3NF"."CE_PRODUCT_SUBCATEGORY" TO bl_cl2;
GRANT SELECT ON "BL_3NF"."CE_PRODUCT_CATEGORY" TO bl_cl2;
GRANT SELECT ON "BL_3NF"."CE_PAY_STATE" TO bl_cl2;
GRANT SELECT ON "BL_3NF"."CE_LOCALIZATION" TO bl_cl2;
GRANT SELECT ON "BL_3NF"."CE_DEPARTMENTS" TO bl_cl2;
GRANT SELECT ON  "BL_3NF"."CE_COUNTRIES" TO bl_cl2;
GRANT SELECT ON "BL_3NF"."CE_CONSUMERS" TO bl_cl2;
GRANT SELECT ON "BL_3NF"."CE_CONSUMER_RATE" TO bl_cl2;
GRANT SELECT ON "BL_3NF"."CE_CITIES" TO bl_cl2;
GRANT SELECT ON "BL_3NF"."CE_OCCUPATION" TO bl_cl2;
GRANT SELECT ON "BL_3NF"."CE_ADDRESSES" TO bl_cl2;
GRANT SELECT ON "BL_3NF"."CE_SUBREGIONS" TO bl_cl2;
GRANT UNLIMITED TABLESPACE TO bl_cl2;
GRANT CREATE ANY TABLE TO bl_cl2;
GRANT EXECUTE ON bl_cl.PKG_DROP TO bl_cl2; 
GRANT EXECUTE ON PKG_DROP.DROP_Proc TO bl_cl2; 

-- Grants to bl_cl
GRANT CREATE ANY SYNONYM TO bl_cl;
GRANT CREATE ANY PROCEDURE TO bl_cl;
GRANT SELECT ON sa_src.ext_products TO bl_cl;

GRANT CREATE ANY SYNONYM TO bl_cl;
GRANT CREATE PUBLIC SYNONYM TO bl_cl2;

-- 3nf
GRANT CREATE PUBLIC SYNONYM TO bl_3nf;

-- 3nf
CREATE OR REPLACE PUBLIC SYNONYM CE_SALES FOR "BL_3NF"."CE_SALES"; 
CREATE OR REPLACE PUBLIC SYNONYM CE_RESPONSIBLE FOR "BL_3NF"."CE_RESPONSIBLE";
CREATE OR REPLACE PUBLIC SYNONYM CE_REGIONS FOR "BL_3NF"."CE_REGIONS";
CREATE OR REPLACE PUBLIC SYNONYM CE_PROMOTIONS FOR "BL_3NF"."CE_PROMOTIONS";
CREATE OR REPLACE PUBLIC SYNONYM CE_PRODUCTS FOR "BL_3NF"."CE_PRODUCTS";
CREATE OR REPLACE PUBLIC SYNONYM CE_PRODUCT_SUBCATEGORY FOR "BL_3NF"."CE_PRODUCT_SUBCATEGORY";
CREATE OR REPLACE PUBLIC SYNONYM CE_PRODUCT_CATEGORY FOR "BL_3NF"."CE_PRODUCT_CATEGORY";
CREATE OR REPLACE PUBLIC SYNONYM CE_PAY_STATE FOR "BL_3NF"."CE_PAY_STATE";
CREATE OR REPLACE PUBLIC SYNONYM CE_LOCALIZATION FOR "BL_3NF"."CE_LOCALIZATION";
CREATE OR REPLACE PUBLIC SYNONYM CE_DEPARTMENTS FOR "BL_3NF"."CE_DEPARTMENTS";
CREATE OR REPLACE PUBLIC SYNONYM CE_COUNTRIES FOR "BL_3NF"."CE_COUNTRIES";
CREATE OR REPLACE PUBLIC SYNONYM CE_CONSUMERS FOR "BL_3NF"."CE_CONSUMERS";
CREATE OR REPLACE PUBLIC SYNONYM CE_CONSUMER_RATE FOR "BL_3NF"."CE_CONSUMER_RATE";
CREATE OR REPLACE PUBLIC SYNONYM CE_CITIES FOR "BL_3NF"."CE_CITIES";
CREATE OR REPLACE PUBLIC SYNONYM CE_OCCUPATION FOR "BL_3NF"."CE_OCCUPATION";
CREATE OR REPLACE PUBLIC SYNONYM CE_ADDRESSES FOR "BL_3NF"."CE_ADDRESSES" ;
CREATE OR REPLACE PUBLIC SYNONYM CE_SUBREGIONS FOR "BL_3NF"."CE_SUBREGIONS" ;