--drop MATERIALIZED view mat_view_comiit;

CREATE MATERIALIZED VIEW LOG ON src2
WITH PRIMARY KEY
   , ROWID
   , SEQUENCE
INCLUDING NEW VALUES;

CREATE MATERIALIZED VIEW mat_view_commit
REFRESH FAST ON COMMIT ENABLE QUERY REWRITE
AS select * from src2;





