@USER_[bl_cl2].sql
CONNECT bl_cl2/123456;
show user;

@DROP_proc(updated).sql
@CLS2_SALES.sql
@CLS2_DATE.sql
@CLS2_PROMOTIONS.sql
@CLS2_PRODUCTS.sql
@CLS2_DEPARTMENTS.sql
@CLS2_CONSUMERS.sql

@CE_[DDL-SYNONYMS].sql
@pkg_DWH_DML.sql

execute DWH_DDL.DIM_CONSUMERS;
execute DWH_DDL.DIM_DEPARTMENTS;
execute DWH_DDL.DIM_PRODUCTS;
execute DWH_DDL.DIM_PROMOTIONS;
execute DWH_DDL.FCT_SALES;



