execute bl_cl.PKG_DROP.DROP_Proc('CLS_DEPARTMENTS','table');
CREATE TABLE "BL_CL2"."CLS_DEPARTMENTS"
(
	"DEPARTMENT_ID" NUMBER(8),
	"DEPARTMENT_DESC" VARCHAR2(50),
	"ADDRESS_ID" VARCHAR2(50),
	"ADDRESS_DESC" VARCHAR2(50),
	"CITY_ID" NUMBER(15),
	"CITY_DESC" VARCHAR2(100),
	"COUNTRY_ID" NUMBER(15),
	"COUNTRY_DESC" VARCHAR2(100),
	"SUBREGION_ID" NUMBER(8),
	"SUBREGION_DESC" VARCHAR2(50),
	"REGION_ID" NUMBER(8),
	"REGION_DESC" VARCHAR2(50),
  "PHONE" VARCHAR2(20),
	"POSTAL_CODE" VARCHAR2(50),
	"START_DT" DATE,
	"END_DT" DATE,
	"IS_ACTIVE" VARCHAR2(1),
	"UPDATE_DT" DATE,
	"INSERT_DT" DATE
)
;