execute bl_cl.PKG_DROP.DROP_Proc('CLS_SALES','table');
CREATE TABLE "BL_CL2"."CLS_SALES"
(
	"PRODUCT_ID" NUMBER(8) NOT NULL,
	"DEPARTMENT_ID" NUMBER(8) NOT NULL,
	"CONSUMER_ID" NUMBER(8) NOT NULL,
	"PROMO_ID" NUMBER(8) NOT NULL,
	"DATE_ID" DATE NOT NULL,
	"COST" NUMBER(8,2),
	"AMOUNT" NUMBER(8,2),
  "UPDATE_DT" DATE,
	"INSERT_DT" DATE
)
;