execute bl_cl.PKG_DROP.DROP_Proc('CLS_PROMOTIONS','table');
CREATE TABLE "BL_CL2"."CLS_PROMOTIONS"
(

	"PROMO_ID" NUMBER(8),
	"PROMO_NAME" VARCHAR2(100),
	"PROMO_DESC" VARCHAR2(100),
	"PROMO_COST" NUMBER(8,2),
	"START_DT" DATE,
	"END_DT" DATE,
	"IS_ACTIVE" VARCHAR(1),
  "UPDATE_DT" DATE,
	"INSERT_DT" DATE
)
;