/**===============================================*\
Name...............:   Cleansing table fct_salesitems BL_DWH layer
Contents...........:   Create table description
Author.............:   Maryna Hlazunova
Date...............:   02-Dec-2017
\*=============================================== */
DROP TABLE fct_salesitems;
--**********************************************

CREATE TABLE fct_salesitems
  (
    DD_ORDER_SRCID         NUMBER(15),
    DIM_ORDER_DATE         DATE,
    DIM_CUSTOMER_SURRID    NUMBER(12,0),
    DIM_PRODUCT_SURRID     NUMBER(10),
    DIM_PAYDELIVERY_SURRID NUMBER(2,0),
    DIM_PICKUPPOINT_SURRID NUMBER(3,0),
    FCT_QUANTITY           NUMBER(20),
    FCT_ITEM_SUM           NUMBER(35,2),
    FCT_DISCOUNT_SUM       NUMBER(35,2),
    FCT_TOTAL_SUM          NUMBER(35,2),
    INSERT_DT              DATE,
    CONSTRAINT FK_DIM_ORDER_DATE FOREIGN KEY (DIM_ORDER_DATE) REFERENCES DIM_DATES (FULL_DATE),
    CONSTRAINT FK_DIM_CUSTOMER_SURRID FOREIGN KEY (DIM_CUSTOMER_SURRID) REFERENCES DIM_CUSTOMERS_SCD (CUSTOMER_SURRID),
    CONSTRAINT FK_DIM_PRODUCT_SURRID FOREIGN KEY (DIM_PRODUCT_SURRID) REFERENCES DIM_PRODUCTS_SCD (PRODUCT_SURRID),
    CONSTRAINT FK_DIM_PAYDELIVERIES_SURRID FOREIGN KEY (DIM_PAYDELIVERY_SURRID) REFERENCES DIM_PAYDELIVERIES (PAYDELIVERY_SURRID),
    CONSTRAINT FK_DIM_PICKUPPOINTS_SURRID FOREIGN KEY (DIM_PICKUPPOINT_SURRID) REFERENCES DIM_PICKUPPOINTS (PICKUPPOINT_SURRID)
  )
  PARTITION BY RANGE
  (
    DIM_ORDER_DATE
  )
  (
    PARTITION before_2013 VALUES LESS THAN (TO_DATE('01.01.2013', 'DD.MM.YYYY')),
    PARTITION before_2014 VALUES LESS THAN (TO_DATE('01.01.2014', 'DD.MM.YYYY')),
    PARTITION before_2015 VALUES LESS THAN (TO_DATE('01.01.2015', 'DD.MM.YYYY')),
    PARTITION before_2016 VALUES LESS THAN (TO_DATE('01.01.2016', 'DD.MM.YYYY')),
    PARTITION before_2017 VALUES LESS THAN (TO_DATE('01.01.2017', 'DD.MM.YYYY')),
    PARTITION before_2018 VALUES LESS THAN (TO_DATE('01.01.2018', 'DD.MM.YYYY')),
    PARTITION before_2019 VALUES LESS THAN (TO_DATE('01.01.2019', 'DD.MM.YYYY')),
    PARTITION before_2020 VALUES LESS THAN (TO_DATE('01.01.2020', 'DD.MM.YYYY')),
    PARTITION after_2020 VALUES LESS THAN (MAXVALUE)
  );

--**********************************************
--select * from fct_salesitems;