CREATE TABLE CE_CITY
  (
    CITY_SRCID NUMBER (8)            NOT NULL,
    CITY       VARCHAR2 (100)         NOT NULL,
    ATE_SRCID  NUMBER (8)            NOT NULL,
    CONSTRAINT "PK_CITY_SRCID" PRIMARY KEY (CITY_SRCID),
    CONSTRAINT "FK_ATE_SRCID" FOREIGN KEY (ATE_SRCID) REFERENCES CE_ATE (ATE_SRCID)
  );