CREATE TABLE wrk_customer (
    ID NUMBER(10),
    L_NAME VARCHAR2(200),
    F_NAME VARCHAR2(200),
    M_PHONE VARCHAR2(200),
    E_MAIL VARCHAR2(200),
    STREET VARCHAR2(200),
    HOUSE VARCHAR2(200),
    FLAT VARCHAR2(200),
    PHONE VARCHAR2(200),
    CITY_NAME VARCHAR2(200),
    COUNTRY_NAME VARCHAR2(200),
    COUNTRY_CODE VARCHAR2(200),
    REGION_NAME VARCHAR2(200),
    CONTINENT_NAME VARCHAR2(200)
    );
    

CREATE TABLE wrk_employees (
    ID NUMBER(30),
    FIRST_NAME VARCHAR2(200),
    LAST_NAME VARCHAR2(200),
    M_PHONE VARCHAR2(200),
    EMAIL VARCHAR2(200),
    JOBS VARCHAR2(200),
    SALARY NUMBER(30),
    STREET VARCHAR2(200),
    HOUSE VARCHAR2(200),
    FLAT VARCHAR2(200),
    PHONE VARCHAR2(200),
    CITY_NAME VARCHAR2(200),
    COUNTRY_NAME VARCHAR2(200),
    COUNTRY_CODE VARCHAR2(200),
    REGION_NAME VARCHAR2(200),
    CONTINENT_NAME VARCHAR2(200),
    STORE_ID NUMBER(10)
    ); 

CREATE TABLE STORES_SRC (
    ID_STORE NUMBER(10),
    STORE_DESC VARCHAR2(250),
    STREET VARCHAR2(70),
    HOUSE NUMBER(5),
    FLAT NUMBER(5),
    PHONE VARCHAR2(30),
    CITY VARCHAR2(70),
    COUNTRY VARCHAR2(70),
    REGION VARCHAR2(70),
    CONTINENT VARCHAR2(70),
    ID_MANAGER NUMBER(10)
    );


DECLARE 
    rand_id INT;
BEGIN
FOR CNT IN 1..20 LOOP
rand_id := TRUNC(DBMS_RANDOM.VALUE(0,200));
INSERT INTO STORES_SRC SELECT * FROM (
    SELECT CNT AS ID, NULL AS STORE_DESC, STREET, TRUNC(DBMS_RANDOM.VALUE(0,200)) AS HOUSE, NULL AS FLAT, TRUNC(DBMS_RANDOM.VALUE(1000000,9999999)) AS PHONE,
        CITY_NAME, COUNTRY_NAME, REGION_NAME, CONTINENT_NAME, (SELECT ID FROM wrk_employees WHERE JOBS = 'Manager' AND STORE_ID = CNT AND ROWNUM = 1) as ID_MANAGER
    FROM wrk_employees
    WHERE ID = rand_id);
END LOOP;
COMMIT;
END;
/

CREATE TABLE WRK_PRODUCTS (
    ID_PROD NUMBER(10),
    PROD_NAME VARCHAR2(100),
    PROD_DESC VARCHAR2(3000),
    PROD_COST NUMBER(10),
    SUBCATEGORY VARCHAR2(100),
    SUBCATEGORY_DESC VARCHAR2(750),
    CATEGORY VARCHAR2(100),
    CATEGORY_DESC VARCHAR2(350)
    );

CREATE TABLE WRK_STORE (
    ID_STORE NUMBER(10),
    STORE_DESC VARCHAR2(250),
    STREET VARCHAR2(70),
    HOUSE NUMBER(5),
    FLAT NUMBER(5),
    PHONE VARCHAR2(30),
    CITY VARCHAR2(70),
    COUNTRY VARCHAR2(70),
    REGION VARCHAR2(70),
    CONTINENT VARCHAR2(70),
    ID_MANAGER NUMBER(10)
    );

