DROP TABLESPACE TBS1 INCLUDING CONTENTS;
DROP TABLESPACE TBS2 INCLUDING CONTENTS;
DROP TABLESPACE TBS3 INCLUDING CONTENTS;
DROP TABLESPACE TBS4 INCLUDING CONTENTS;
DROP TABLESPACE TBS5 INCLUDING CONTENTS;
DROP TABLESPACE TBS6 INCLUDING CONTENTS;
DROP TABLESPACE TBS7 INCLUDING CONTENTS;
DROP TABLESPACE TBS8 INCLUDING CONTENTS;