CREATE TABLE dim_products_scd (
    product_surr_id     NUMBER(10) NOT NULL,
    product_id          NUMBER(10) NOT NULL,
    product_desc        VARCHAR2(10 BYTE) NOT NULL,
    product_desc_full   VARCHAR2(40 BYTE) NOT NULL,
    line_name           VARCHAR2(10 BYTE) NOT NULL,
    line_description    VARCHAR2(40 BYTE) NOT NULL,
    season              VARCHAR2(10 BYTE) NOT NULL,
    collection_desc     VARCHAR2(40 BYTE) NOT NULL,
    collection_dt       DATE NOT NULL,
    product_type        VARCHAR2(10 BYTE) NOT NULL,
    height              VARCHAR2(10 BYTE) DEFAULT '-99',
    hip_girth           NUMBER(10) DEFAULT '-99',
    bra_size_uk         VARCHAR2(10 BYTE) DEFAULT '-99',
    bra_size_usa        VARCHAR2(10 BYTE) DEFAULT '-99',
    bra_size_eu         VARCHAR2(10 BYTE) DEFAULT '-99',
    bra_size_fr         VARCHAR2(10 BYTE) DEFAULT '-99',
    bra_size_uie        VARCHAR2(10 BYTE) DEFAULT '-99',
    panties_size_uk     VARCHAR2(10 BYTE) DEFAULT '-99',
    panties_size_usa    VARCHAR2(10 BYTE) DEFAULT '-99',
    panties_size_eu     VARCHAR2(10 BYTE) DEFAULT '-99',
    panties_size_fr     VARCHAR2(10 BYTE) DEFAULT '-99',
    panties_size_uie    VARCHAR2(10 BYTE) DEFAULT '-99',
    color               VARCHAR2(40 BYTE),
    price               NUMBER(10),
    start_dt            DATE NOT NULL,
    end_dt              DATE NOT NULL,
    is_active           VARCHAR2(4) NOT NULL,
    CONSTRAINT product_surr_id_pk PRIMARY KEY ( product_surr_id )
);