CREATE TABLE CE_ADDRESS
  (
    ADDRESS_SRCID NUMBER (8)         NOT NULL,
    ADDRESS       VARCHAR2 (100)      NOT NULL,
    POSTAL_CODE   NUMBER (8)         NOT NULL,
    CITY_SRCID    NUMBER (8)         NOT NULL,
    CONSTRAINT "PK_ADDRESS_SRCID" PRIMARY KEY (ADDRESS_SRCID),
    CONSTRAINT "FK_CITY_SRCID" FOREIGN KEY (CITY_SRCID) REFERENCES CE_CITY (CITY_SRCID)
  );