/*drop user FRAMEWORK;
drop user SRC CASCADE;
drop user BL_CL CASCADE;
drop user BL_3NF CASCADE;*/

/*CREATE USER FRAMEWORK 
  IDENTIFIED BY 123456 
  DEFAULT TABLESPACE users 
  QUOTA UNLIMITED ON users 
  TEMPORARY TABLESPACE temp 
  PROFILE default; 
--  GRANT conn TO BL_CL;
*/

CREATE USER SRC 
  IDENTIFIED BY 123456 
  DEFAULT TABLESPACE users 
  QUOTA UNLIMITED ON users 
  TEMPORARY TABLESPACE temp 
  PROFILE default; 
  --GRANT conn TO SRC;

--drop user BL_CL CASCADE;

CREATE USER BL_CL 
  IDENTIFIED BY 123456 
  DEFAULT TABLESPACE users 
  QUOTA UNLIMITED ON users 
  TEMPORARY TABLESPACE temp 
  PROFILE default; 
--  GRANT conn TO BL_CL;

CREATE USER BL_3NF 
  IDENTIFIED BY 123456 
  DEFAULT TABLESPACE users 
  QUOTA UNLIMITED ON users 
  TEMPORARY TABLESPACE temp 
  PROFILE default; 
--  GRANT conn TO BL_3NF;

CREATE USER BL_CL_DM 
  IDENTIFIED BY 123456 
  DEFAULT TABLESPACE users 
  QUOTA UNLIMITED ON users 
  TEMPORARY TABLESPACE temp 
  PROFILE default; 
  
CREATE USER BL_DM
  IDENTIFIED BY 123456 
  DEFAULT TABLESPACE users 
  QUOTA UNLIMITED ON users 
  TEMPORARY TABLESPACE temp 
  PROFILE default; 
