create view SALES_VIEW as 
select PROD_NAME PRODUCT, 
       COUNTRY_NAME COUNTRY,
       CHANNEL_ID CHANNEL,
       SUBSTR(CALENDAR_QUARTER_DESC, 6,2) QUARTER,
       SUM(AMOUNT_SOLD) AMOUNT_SOLD,
       SUM(QUANTITY_SOLD) QUANTITY_SOLD 
from sh.SALES, sh.TIMES, sh.CUSTOMERS, sh.COUNTRIES, sh.PRODUCTS 
where sh.SALES.TIME_ID = sh.TIMES.TIME_ID and
      sh.SALES.PROD_ID = sh.PRODUCTS.PROD_ID and
      sh.SALES.CUST_ID = sh.CUSTOMERS.CUST_ID and
      sh.CUSTOMERS.COUNTRY_ID = sh.COUNTRIES.COUNTRY_ID 
group by PROD_NAME, COUNTRY_NAME, CHANNEL_ID, SUBSTR(CALENDAR_QUARTER_DESC, 6, 2) ;

select * from sales_view;
select * from (select COUNTRY, CHANNEL, AMOUNT_SOLD from SALES_VIEW) S 
PIVOT (SUM(AMOUNT_SOLD) for CHANNEL in (2 as PARTNERS, 3 as DIRECT_SALES, 4 as INTERNET_SALES, 9 as TELESALES)) 
order by COUNTRY;
