CONNECT bl_cl/123456;
show user;

@USER_[bl_3nf].sql;
@bl_cl_[DDL_DROP_3nf].sql;

@CE_PROMOTIONS.sql
@CE_CONSUMER_RATE.sql
@CE_CONSUMERS.sql
@CE_RESPONSIBLE.sql
@CE_OCCUPATION.sql
@CE_PRODUCTS.sql
@CE_LOCALIZATION.sql
@CE_PRODUCT_SUBCATEGORY.sql
@CE_PROUCT_CATEGORY.sql
@CE_DEPARTMENTS.sql
@CE_ADDRESSES.sql
@CE_CITIES.sql
@CE_COUNTRIES.sql
@CE_SUBREGION.sql
@CE_REGIONS.sql
@CE_SALES.sql

@CE_[DDL-CONSTRAINTS].sql
@CE_[DDL-SYNONYMS].sql

@bl_cl_[DML-CE].sql
