---- 3nf
execute pkg_drop.DROP_Proc('bl_3nf.ADDRESSES','table');
execute pkg_drop.DROP_Proc('bl_3nf.CITIES','table');
execute pkg_drop.DROP_Proc('bl_3nf.CONSUMER_RATE','table');
execute pkg_drop.DROP_Proc('bl_3nf.CONSUMERS','table');
execute pkg_drop.DROP_Proc('bl_3nf.COUNTRIES','table');
execute pkg_drop.DROP_Proc('bl_3nf.DEPARTMENTS','table');
execute pkg_drop.DROP_Proc('bl_3nf.LOCALIZATION','table');
execute pkg_drop.DROP_Proc('bl_3nf.PACKAGE','table');
execute pkg_drop.DROP_Proc('bl_3nf.PAYMENTS','table');
execute pkg_drop.DROP_Proc('bl_3nf.PRODUCT_CATEGORY','table');
execute pkg_drop.DROP_Proc('bl_3nf.PRODUCT_SUBCATEGORY','table');
execute pkg_drop.DROP_Proc('bl_3nf.PRODUCTS','table');
execute pkg_drop.DROP_Proc('bl_3nf.PROMOTIONS','table');
execute pkg_drop.DROP_Proc('bl_3nf.REGIONS','table');
execute pkg_drop.DROP_Proc('bl_3nf.RESPONSIBLE','table');
execute pkg_drop.DROP_Proc('bl_3nf.SALES','table');
execute pkg_drop.DROP_Proc('bl_3nf.RESPONSIBLE','table');
