---------------------------------------------------------------------------------------------
-- CONSTRAINTS-------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------

ALTER TABLE "BL_3NF"."CE_SALES" 
 ADD CONSTRAINT "PK_SALES"
	PRIMARY KEY ("SALE_ID") USING INDEX
;

ALTER TABLE "BL_3NF"."CE_RESPONSIBLE" 
 ADD CONSTRAINT "PK_RESPONSIBLE"
	PRIMARY KEY ("RESP_ID") USING INDEX
;

ALTER TABLE "BL_3NF"."CE_REGIONS" 
 ADD CONSTRAINT "PK_REGIONS"
	PRIMARY KEY ("REGION_ID") USING INDEX
;

ALTER TABLE "BL_3NF"."CE_PROMOTIONS" 
 ADD CONSTRAINT "PK_PROMOTIONS"
	PRIMARY KEY ("PROMO_ID") USING INDEX
;

ALTER TABLE "BL_3NF"."CE_PRODUCTS" 
 ADD CONSTRAINT "PK_PRODUCTS"
	PRIMARY KEY ("PRODUCT_ID") USING INDEX
;

ALTER TABLE "BL_3NF"."CE_PRODUCT_SUBCATEGORY" 
 ADD CONSTRAINT "PK_PRODUCT_SUBC_01"
	PRIMARY KEY ("SUBCATEGORY_ID") USING INDEX
;

ALTER TABLE "BL_3NF"."CE_PRODUCT_CATEGORY" 
 ADD CONSTRAINT "PK_PRODUCT_CATEGORY"
	PRIMARY KEY ("CATEGORY_ID") USING INDEX
;

ALTER TABLE "BL_3NF"."CE_LOCALIZATION" 
 ADD CONSTRAINT "PK_LOCALIZATION"
	PRIMARY KEY ("LOCALIZATION_ID") USING INDEX
;

ALTER TABLE "BL_3NF"."CE_DEPARTMENTS" 
 ADD CONSTRAINT "PK_DEPARTMENTS"
	PRIMARY KEY ("DEPARTMENT_ID") USING INDEX
;

ALTER TABLE "BL_3NF"."CE_COUNTRIES" 
 ADD CONSTRAINT "PK_COUNTRIES"
	PRIMARY KEY ("COUNTRY_ID") USING INDEX
;

ALTER TABLE "BL_3NF"."CE_CONSUMERS" 
 ADD CONSTRAINT "PK_CONSUMERS"
	PRIMARY KEY ("CONSUMER_ID") USING INDEX
;

ALTER TABLE "BL_3NF"."CE_CONSUMER_RATE"  
 ADD CONSTRAINT "PK_CONSUMER_RATE"
	PRIMARY KEY ("CONSUMER_RATE_ID") USING INDEX
;

ALTER TABLE "BL_3NF"."CE_CITIES" 
 ADD CONSTRAINT "PK_CITIES"
	PRIMARY KEY ("CITY_ID") USING INDEX
;

ALTER TABLE "BL_3NF"."CE_OCCUPATION" 
 ADD CONSTRAINT "PK_BL_3NF."
	PRIMARY KEY ("OCCUPATION_ID") USING INDEX
;

ALTER TABLE "BL_3NF"."CE_ADDRESSES" 
 ADD CONSTRAINT "PK_ADDRESSES"
	PRIMARY KEY ("ADDRESS_ID") USING INDEX
;

ALTER TABLE "BL_3NF"."CE_SUBREGIONS"
 ADD CONSTRAINT "PK_SUBREGIONS"
  PRIMARY KEY ("SUBREGION_ID") USING INDEX
;

-- 3nf
--------------------------------------------------------------------------------
ALTER TABLE "BL_3NF"."CE_SALES" 
 ADD CONSTRAINT "FK_SALES_CONSUMERS"
	FOREIGN KEY ("CONSUMER_ID") REFERENCES "BL_3NF"."CE_CONSUMERS" ("CONSUMER_ID")
;

ALTER TABLE "BL_3NF"."CE_SALES" 
 ADD CONSTRAINT "FK_SALES_DEPARTMENTS"
	FOREIGN KEY ("DEPARTMENT_ID") REFERENCES "BL_3NF"."CE_DEPARTMENTS" ("DEPARTMENT_ID")
;

ALTER TABLE "BL_3NF"."CE_SALES" 
 ADD CONSTRAINT "FK_SALES_PRODUCTS"
	FOREIGN KEY ("PRODUCT_ID") REFERENCES "BL_3NF"."CE_PRODUCTS" ("PRODUCT_ID")
;

ALTER TABLE "BL_3NF"."CE_SALES" 
 ADD CONSTRAINT "FK_SALES_PROMOTIONS"
	FOREIGN KEY ("PROMO_ID") REFERENCES "BL_3NF"."CE_PROMOTIONS" ("PROMO_ID")
;

ALTER TABLE "BL_3NF"."CE_RESPONSIBLE" 
 ADD CONSTRAINT "FK_RESPONSIBLE_OCCUPATION"
	FOREIGN KEY ("OCCUPATION_ID") REFERENCES "BL_3NF"."CE_OCCUPATION" ("OCCUPATION_ID")
;

ALTER TABLE "BL_3NF"."CE_PRODUCTS" 
 ADD CONSTRAINT "FK_PRODUCTS_LOCALIZATION"
	FOREIGN KEY ("LOCALIZATION_ID") REFERENCES "BL_3NF"."CE_LOCALIZATION" ("LOCALIZATION_ID")
;

ALTER TABLE "BL_3NF"."CE_PRODUCTS" 
 ADD CONSTRAINT "FK_PRODUCTS_PRODUCT_CATEGORY"
	FOREIGN KEY ("CATEGORY_ID") REFERENCES "BL_3NF"."CE_PRODUCT_CATEGORY" ("CATEGORY_ID")
;

ALTER TABLE "BL_3NF"."CE_PRODUCT_SUBCATEGORY" 
 ADD CONSTRAINT "FK_PRODUCT_SUBC_PRODUCT_CAT_01"
	FOREIGN KEY ("CATEGORY_ID") REFERENCES "BL_3NF"."CE_PRODUCT_CATEGORY" ("CATEGORY_ID")
;

ALTER TABLE "BL_3NF"."CE_DEPARTMENTS" 
 ADD CONSTRAINT "FK_DEPARTMENTS_ADDRESSES"
	FOREIGN KEY ("ADDRESS_ID") REFERENCES "BL_3NF"."CE_ADDRESSES" ("ADDRESS_ID")
;

ALTER TABLE "BL_3NF"."CE_COUNTRIES" 
 ADD CONSTRAINT "FK_COUNTRIES_SUBREGIONS"
	FOREIGN KEY ("SUBREGION_ID") REFERENCES "BL_3NF"."CE_SUBREGIONS" ("SUBREGION_ID")
;

ALTER TABLE "BL_3NF"."CE_CONSUMERS" 
 ADD CONSTRAINT "FK_CONSUMERS_ADDRESSES"
	FOREIGN KEY ("ADDRESS_ID") REFERENCES "BL_3NF"."CE_ADDRESSES" ("ADDRESS_ID")
;

ALTER TABLE "BL_3NF"."CE_CONSUMERS" 
 ADD CONSTRAINT "FK_CONSUMERS_CONSUMER_RATE"
	FOREIGN KEY ("CONSUMER_RATE_ID") REFERENCES "BL_3NF"."CE_CONSUMER_RATE" ("CONSUMER_RATE_ID")
;

ALTER TABLE "BL_3NF"."CE_CONSUMERS" 
 ADD CONSTRAINT "FK_CONSUMERS_RESPONSIBLE"
	FOREIGN KEY ("RESP_ID") REFERENCES "BL_3NF"."CE_RESPONSIBLE" ("RESP_ID")
;

ALTER TABLE "BL_3NF"."CE_CITIES" 
 ADD CONSTRAINT "FK_CITIES_COUNTRIES"
	FOREIGN KEY ("COUNTRY_ID") REFERENCES "BL_3NF"."CE_COUNTRIES" ("COUNTRY_ID")
;

ALTER TABLE "BL_3NF"."CE_ADDRESSES" 
 ADD CONSTRAINT "FK_ADDRESSES_CITIES"
	FOREIGN KEY ("CITY_ID") REFERENCES "BL_3NF"."CE_CITIES" ("CITY_ID")
;

ALTER TABLE "BL_3NF"."CE_SUBREGIONS" 
 ADD CONSTRAINT "FK_SUBREGIONS_REGIONS"
	FOREIGN KEY ("REGION_ID") REFERENCES "BL_3NF"."CE_REGIONS" ("REGION_ID")
;