-- CE_CONSUMERS
execute pkg_drop.DROP_proc('"BL_3NF"."CE_CONSUMERS"','table');
CREATE TABLE "BL_3NF"."CE_CONSUMERS"
(
	"CONSUMER_ID" NUMBER(12) NOT NULL,
	"CONSUMER_CODE" VARCHAR2(30),
	"CONSUMER_TITLE" VARCHAR2(100),
	"CONSUMER_RATE_ID" NUMBER(12),
	"ADDRESS_ID" NUMBER(12),
	"RESP_ID" NUMBER(12),
	"UPDATE_DT" DATE,
	"INSERT_DT" DATE DEFAULT TRUNC(SYSDATE)
)
;

execute pkg_drop.DROP_proc('seq_consumer','sequence');
CREATE SEQUENCE seq_consumer
      INCREMENT BY 1 
          START WITH 1 
       MINVALUE 1 
        NOCYCLE; 