-- CE_PRODUCT_CATEGORY
execute pkg_drop.DROP_proc('"BL_3NF"."CE_PRODUCT_CATEGORY"','table');
CREATE TABLE "BL_3NF"."CE_PRODUCT_CATEGORY"
(
	"CATEGORY_ID" NUMBER(8,2) NOT NULL,
	"CATEGORY_CODE" VARCHAR2(50),
	"CATEGORY_NAME" VARCHAR2(50),
	"UPDATE_DT" DATE,
	"INSERT_DT" DATE DEFAULT TRUNC(SYSDATE)
)
;

execute pkg_drop.DROP_proc('seq_product_category','sequence');
CREATE SEQUENCE seq_product_category
      INCREMENT BY 1 
          START WITH 1 
       MINVALUE 1 
        NOCYCLE; 