-- CE_PROMOTIONS
execute pkg_drop.DROP_proc('"BL_3NF"."CE_PROMOTIONS"','table');
CREATE TABLE "BL_3NF"."CE_PROMOTIONS"
(
	"PROMO_ID" NUMBER(8,2) NOT NULL,
	"PROMO_CODE" VARCHAR2(50),
	"PROMO_NAME" VARCHAR2(50),
	"PROMO_DESC" VARCHAR2(50),
  "PROMO_COST" NUMBER(8,2),
	"START_DT" DATE,
	"END_DT" DATE,
	"IS_ACTIVE" VARCHAR2(1),
	"UPDATE_DT" DATE,
	"INSERT_DT" DATE 
)
;

execute pkg_drop.DROP_proc('seq_promotion','sequence');
CREATE SEQUENCE seq_promotion
      INCREMENT BY 1 
          START WITH 1 
       MINVALUE 1 
        NOCYCLE; 