-- CE_SUBREGIONS
execute pkg_drop.DROP_proc('"BL_3NF"."CE_SUBREGIONS"','table');
CREATE TABLE "BL_3NF"."CE_SUBREGIONS"
(
	"SUBREGION_ID" NUMBER(8,2) NOT NULL,
	"SUBREGION_CODE" VARCHAR2(4),
	"SUBREGION_NAME" VARCHAR2(100),
	"REGION_ID" NUMBER(8,2),
	"UPDATE_DT" DATE,
	"INSERT_DT" DATE DEFAULT TRUNC(SYSDATE)
)
;

execute pkg_drop.DROP_proc('seq_subregions','sequence');
CREATE SEQUENCE seq_subregions
      INCREMENT BY 1 
          START WITH 1 
       MINVALUE 1 
        NOCYCLE;