--select * from CL_PAYMENT;
 exec  FRAMEWORK.pkg_utl_drop.proc_drop_obj ('Cl_Payment', 'TABLE');
CREATE TABLE Cl_Payment
(
	ID_PAYMENT NUMBER(16) ,--NOT NULL,
	--ID_CURRENCY VARCHAR2(3) NOT NULL,
	ID_CUSTOMER NUMBER(10),
	ID_PAYMENT_TYPE NUMBER(2) NOT NULL,
  ID_STATION NUMBER(4) NOT NULL,
  ID_FUEL_CODE NUMBER(3) NOT NULL,
  
	PAYMENT_DATE DATE NOT NULL,
	PRICE NUMBER(8,2) NOT NULL,
  QUANTITY NUMBER(10,3) NOT NULL,
	PAYMENT_TIME VARCHAR2(10)--TIMESTAMP(6)
)
;