DROP TABLE DIM_CARS CASCADE CONSTRAINTS;
CREATE TABLE DIM_CARS(
    CAR_ID	            NUMBER NOT NULL,
    CAR_NUMBER	        NUMBER(8) NOT NULL, 
    CAR_NAME	        VARCHAR2(200) NOT NULL,
    CAR_REGISTRATION_DT DATE          NOT NULL,
    VEHICLE_TYPE_NAME   VARCHAR2(200) NOT NULL,
    ENGINE_TYPE_NAME	VARCHAR2(200) NOT NULL,
    GEARBOX_TYPE_NAME	VARCHAR2(200) NOT NULL,
    BRAND_NAME	        VARCHAR2(200) NOT NULL,
    MODEL_NAME	        VARCHAR2(200) NOT NULL,
    REPAIR_STATUS_NAME	VARCHAR2(200) NOT NULL,
    POWER_PS            NUMBER(8)     NOT NULL,
    KILOMETERS          NUMBER(8)     NOT NULL,
    IS_ACTIVE           VARCHAR2(4)   NOT NULL,
    INSERT_DT           DATE          NOT NULL,
    UPDATE_DT           DATE          NOT NULL,
    CONSTRAINT CAR_ID PRIMARY KEY (CAR_ID));