CREATE TABLE CE_PRODUCT_SUBCATEGORY
  (
    SUBCATEGORY_SRCID NUMBER (8)     NOT NULL,
    SUBCATEGORY_NAME  VARCHAR2 (100)  NOT NULL,
    CATEGORY_SRCID    NUMBER (8)     NOT NULL,
    CONSTRAINT "PK_SUBCATEGORY_SRCID" PRIMARY KEY (SUBCATEGORY_SRCID),
    CONSTRAINT "FK_CATEGORY_SRCID" FOREIGN KEY (CATEGORY_SRCID) REFERENCES CE_PRODUCT_CATEGORY (CATEGORY_SRCID)
  );