CREATE TABLE FCT_SALES_DD
(
	"PRODUCT_ID" NUMBER(8) NOT NULL,
	"DATE_ID" DATE NOT NULL,
	"CUSTOMER_ID" NUMBER(8) NOT NULL,
	"STORE_ID" NUMBER(8) NOT NULL,
	"EMPLOYEE_ID" NUMBER(8) NOT NULL,
	"AMOUNT_OF_SOLD_ITEMS" NUMBER(8,2) NOT NULL,
	"UNIT COST" NUMBER(5,2) NOT NULL,
	"TOTAL COST" NUMBER(5,2) NOT NULL,
	"SALE_ID" NUMBER(8) NOT NULL,
	INSERT_DT DATE )
;

ALTER TABLE FCT_SALES_DD
 ADD CONSTRAINT "PK_FCT_SALES_DD"
	PRIMARY KEY ("PRODUCT_ID") USING INDEX;
ALTER TABLE FCT_SALES_DD
 ADD CONSTRAINT "FK_FACT_SALES_DIM_CUSTOMERS"
	FOREIGN KEY ("CUSTOMER_ID") REFERENCES "DIM_CUSTOMERS_SCD" ("CUSTOMER_SURR_ID");
ALTER TABLE FCT_SALES_DD
 ADD CONSTRAINT "FK_FACT_SALES_DIM_DATES"
	FOREIGN KEY ("DATE_ID") REFERENCES "DIM_DATES" ("DATE_ID")
;
ALTER TABLE FCT_SALES_DD
 ADD CONSTRAINT "FK_FACT_SALES_DIM_EMPLOYEES"
	FOREIGN KEY ("EMPLOYEE_ID") REFERENCES "DIM_EMPLOYEES" ("EMPLOYEE_SURR_ID")
;
ALTER TABLE FCT_SALES_DD
 ADD CONSTRAINT "FK_FACT_SALES_DIM_PRODUCTS02"
	FOREIGN KEY ("PRODUCT_ID") REFERENCES "DIM_PRODUCTS_SCD" ("PRODUCT_ID")
;
ALTER TABLE FCT_SALES_DD
 ADD CONSTRAINT "FK_FACT_SALES_DIM_STORES"
	FOREIGN KEY ("STORE_ID") REFERENCES "DIM_STORES" ("STORE_SURR_ID")
;
