  CREATE USER Olga_Hilko 
  IDENTIFIED BY 123456 
  DEFAULT TABLESPACE users 
  QUOTA UNLIMITED ON users 
  TEMPORARY TABLESPACE temp 
  PROFILE default; 
  
  GRANT CONNECT, RESOURCE TO Olga_Hilko;
  GRANT CREATE VIEW TO Olga_Hilko;
  GRANT CREATE SYNONYM TO Olga_Hilko;
  
  --DROP USER Olga_Hilko CASCADE;
 --CREATE ROLE conn;
-- CONNECT Olga_Hilko/123456;

  