CREATE TABLE CUSTOMERS (
    ID_CUSTOMER NUMBER(25) PRIMARY KEY,
    CUSTOMER_KEY NUMBER(25) NOT NULL,
    FIRST_NAME VARCHAR2(70) NOT NULL,
    LAST_NAME VARCHAR2(70) NOT NULL,
    MOBILE_PHONE VARCHAR(30) NOT NULL,
    ADDRESS VARCHAR2(100) NOT NULL,
    LOCATION VARCHAR2(300) NOT NULL,
    START_DT DATE NOT NULL,
    END_DT DATE NOT NULL
    );
    
    
CREATE TABLE EMPLOYEES (
    ID_EMPLOYEE NUMBER(25) PRIMARY KEY,
    EMPLOYEE_KEY NUMBER(25) NOT NULL,
    FIRST_NAME VARCHAR2(70) NOT NULL,
    LAST_NAME VARCHAR2(70) NOT NULL,
    JOB_NAME VARCHAR2(50) NOT NULL,
    SALARY NUMBER(15) NOT NULL,
    MANAGER_ID NUMBER(25) NOT NULL,
    MOBILE_PHONE VARCHAR(30) NOT NULL,
    ADDRESS VARCHAR2(100) NOT NULL,
    LOCATION VARCHAR2(300) NOT NULL,
    START_DT DATE NOT NULL,
    END_DT DATE NOT NULL
    );


CREATE TABLE STORES (
    ID_STORE NUMBER(10) PRIMARY KEY,
    STORE_KEY NUMBER(10) NOT NULL,
    STORE_DESC VARCHAR2(500) NOT NULL,
    PHONE VARCHAR(30) NOT NULL,
    ADDRESS VARCHAR2(250) NOT NULL,
    LOCATION VARCHAR2(350) NOT NULL,
    ID_MANAGER NUMBER(25),
    MANAGER_NAME VARCHAR2(150)
    );


CREATE TABLE PRODUCTS (
    ID_PRODUCT NUMBER(15) PRIMARY KEY,
    PRODUCT_KEY NUMBER(15) NOT NULL,
    PRODUCT_NAME VARCHAR2(100) NOT NULL,
    PRODUCS_COST NUMBER(25) NOT NULL,
    SUBCATEGORY_NAME VARCHAR2(100) NOT NULL,
    CATEGORY_NAME VARCHAR2(100) NOT NULL,
    PRODUCT_DESC VARCHAR2(3000) NOT NULL,
    SUBCATEGORY_DESC VARCHAR2(750) NOT NULL,
    CATEGORY_DESC VARCHAR2(500) NOT NULL
    );
    
    
DROP TABLE FACTSALES;
CREATE TABLE FACTSALES (
    ID_SALES NUMBER(30) PRIMARY KEY,
    SALES_KEY NUMBER(30) NOT NULL,
    ID_CUSTOMER NUMBER(25) NOT NULL,
    ID_EMPLOYEE NUMBER(15) NOT NULL,
    ID_STORE NUMBER(15) NOT NULL,
    ID_PRODUCT NUMBER(15) NOT NULL,
    ID_DATE DATE NOT NULL,
    TIME_SALE TIMESTAMP NOT NULL,
    AMOUNT NUMBER(15)
    )
    PARTITION BY RANGE (ID_DATE)
        (PARTITION sales_2014 VALUES LESS THAN (TO_DATE('01.01.2014', 'DD.MM.YYYY')),
         PARTITION sales_2015 VALUES LESS THAN (TO_DATE('01.01.2015', 'DD.MM.YYYY')),
         PARTITION sales_2016 VALUES LESS THAN (TO_DATE('01.01.2016', 'DD.MM.YYYY')),
         PARTITION sales_2017 VALUES LESS THAN (TO_DATE('01.01.2017', 'DD.MM.YYYY')),
         PARTITION sales_max VALUES LESS THAN (MAXVALUE)
    );
    

ALTER TABLE FACTSALES ADD CONSTRAINT id_fact_cust FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMERS (ID_CUSTOMER);
ALTER TABLE FACTSALES ADD CONSTRAINT id_fact_empl FOREIGN KEY (ID_EMPLOYEE) REFERENCES EMPLOYEES (ID_EMPLOYEE);
ALTER TABLE FACTSALES ADD CONSTRAINT id_fact_prod FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCTS (ID_PRODUCT);
ALTER TABLE FACTSALES ADD CONSTRAINT id_fact_store FOREIGN KEY (ID_STORE) REFERENCES STORES (ID_STORE);
ALTER TABLE FACTSALES ADD CONSTRAINT id_fact_date FOREIGN KEY (ID_DATE) REFERENCES DimDATE (DATE_ID);
