exec  FRAMEWORK.pkg_utl_drop.proc_drop_obj ('WRK_INDIVIDUAL', 'TABLE');
exec  FRAMEWORK.pkg_utl_drop.proc_drop_obj ('WRK_Customer', 'TABLE');
exec  FRAMEWORK.pkg_utl_drop.proc_drop_obj ('WRK_Organization', 'TABLE');
exec  FRAMEWORK.pkg_utl_drop.proc_drop_obj ('CL_INDIVIDUAL', 'TABLE');
exec  FRAMEWORK.pkg_utl_drop.proc_drop_obj ('CL_Customer', 'TABLE');
exec  FRAMEWORK.pkg_utl_drop.proc_drop_obj ('CL_Organization', 'TABLE');
exec  FRAMEWORK.pkg_utl_drop.proc_drop_obj ('CL_CUSTOMER_TYPE', 'TABLE');



CREATE TABLE WRK_Individual
(
	CUSTOMER_NK VARCHAR2(50) NOT NULL ,
	FIRST_NAME VARCHAR2(50) NOT NULL,
	LAST_NAME VARCHAR2(50) NOT NULL,
	MIDDLE_NAME VARCHAR2(50) NOT NULL,
	BIRTHDAY DATE NOT NULL,
	SEX NUMBER(1) NOT NULL,
  VEHICLE_DESC VARCHAR2(50),
  VEHICLE_YEAR number(4)
)
;

CREATE TABLE WRK_Customer
(
	CUSTOMER_NK VARCHAR2(50) NOT NULL,
	ID_CUSTOMER_TYPE NUMBER(1) NOT NULL,
	ID_LOCATION NUMBER(10),
	ADDRESS VARCHAR2(50),
	PHONE VARCHAR2(50),
	POSTALCODE NUMBER(8),
	EMAIL VARCHAR2(50),
  START_DATE DATE NOT NULL,
  END_DATE DATE NOT NULL
)
;

CREATE TABLE WRK_Organization
(
	ID_CUSTOMER NUMBER(10),
	RUS_FULL_NAME VARCHAR2(400) NOT NULL,
	--RUS_SHORT_NAME VARCHAR2(50),
	CONTACT VARCHAR2(255),
  MANAGER_FIRST_NAME VARCHAR2(50),
	MANAGER_LAST_NAME VARCHAR2(50),
	MANAGER_MIDDLE_NAME VARCHAR2(50),
  TAX_ID NUMBER(10) NOT NULL,
  MNS_NAME VARCHAR2(255) NOT NULL,
  MNS_NUM NUMBER(10) NOT NULL
)
;


CREATE TABLE CL_Individual
(
	CUSTOMER_NK VARCHAR2(50) NOT NULL ,
	FIRST_NAME VARCHAR2(50) NOT NULL,
	LAST_NAME VARCHAR2(50) NOT NULL,
	MIDDLE_NAME VARCHAR2(50) NOT NULL,
	BIRTHDAY DATE NOT NULL,
	SEX NUMBER(1) NOT NULL,
  VEHICLE_DESC VARCHAR2(50),
  VEHICLE_YEAR number(4)
)
;


CREATE TABLE CL_Customer
(
	CUSTOMER_NK VARCHAR2(50) NOT NULL,
	ID_CUSTOMER_TYPE NUMBER(1) NOT NULL,
	ID_LOCATION NUMBER(10),
	ADDRESS VARCHAR2(50),
	PHONE VARCHAR2(50),
	POSTALCODE NUMBER(8),
	EMAIL VARCHAR2(50),
  START_DATE DATE NOT NULL -- END_DATE DATE 
)
;

CREATE TABLE CL_Organization
(
	--ID_CUSTOMER NUMBER(10) NOT NULL,
	RUS_FULL_NAME VARCHAR2(400) NOT NULL,
/*	CONTACT VARCHAR2(255),
  MANAGER_FIRST_NAME VARCHAR2(50),
	MANAGER_LAST_NAME VARCHAR2(50),
	MANAGER_MIDDLE_NAME VARCHAR2(50),*/
  TAX_ID NUMBER(10) NOT NULL,
  MNS_NAME VARCHAR2(255) NOT NULL,
  MNS_NUM NUMBER(10) NOT NULL
)
;

CREATE TABLE CL_Customer_Type
(
	ID_CUSTOMER_TYPE NUMBER(1) NOT NULL,
	DESCRIPTION VARCHAR2(50) NOT NULL
)
;



