--GRANTS
--exec example: grant_proc(grant_name, schema, object, User_name)
CREATE OR REPLACE PACKAGE pckg_grant AUTHID CURRENT_USER
AS
  PROCEDURE GRANT_PROC(
      GRANT_NAME  IN VARCHAR2,
      SCHEMA_NAME IN VARCHAR2,
      OBJECT_NAME IN VARCHAR2,
      USER_NAME   IN VARCHAR2);
  PROCEDURE GRANT_PROC(
      GRANT_NAME IN VARCHAR2,
      USER_NAME  IN VARCHAR2,
      WAO        IN BOOLEAN := FALSE);
END pckg_grant;
/
CREATE OR REPLACE PACKAGE BODY pckg_grant
AS
PROCEDURE GRANT_PROC(
    GRANT_NAME  IN VARCHAR2,
    SCHEMA_NAME IN VARCHAR2,
    OBJECT_NAME IN VARCHAR2,
    USER_NAME   IN VARCHAR2 )
IS
BEGIN
  EXECUTE IMMEDIATE ('GRANT ' || GRANT_NAME || ' ON ' || SCHEMA_NAME || '.' || OBJECT_NAME || ' TO ' || USER_NAME);
END GRANT_PROC;
PROCEDURE GRANT_PROC(
    GRANT_NAME VARCHAR2,
    USER_NAME  VARCHAR2,
    WAO IN BOOLEAN := FALSE)
IS
BEGIN
  IF WAO THEN
    EXECUTE IMMEDIATE ('GRANT ' || GRANT_NAME || ' TO ' || USER_NAME || ' WITH ADMIN OPTION');
  END IF;
  EXECUTE IMMEDIATE ('GRANT ' || GRANT_NAME || ' TO ' || USER_NAME);
END;
END pckg_grant;
/