-- dim_DATE
execute bl_cl.PKG_DROP.DROP_Proc('"DWH"."DIM_DATE"','table');
CREATE TABLE "DWH"."DIM_DATE"
(
	"DATE_ID" DATE NOT NULL,
	"DAY_WEEK" NUMBER(8),
	"DAY_SHORT" VARCHAR2(50),
	"DAY_LONG" VARCHAR2(50),
	"DAY_MONTH" NUMBER(8,2),
	"LASTDAY_MONTH" DATE,
	"DAY_YEAR" NUMBER(8),
	"MONTH_YEAR" NUMBER(8),
	"MONTH_SHORT" VARCHAR2(50),
	"MONTH_LONG" VARCHAR2(50),
	"MONTH_DESC" VARCHAR2(50),
	"QUARTER" NUMBER(8),
	"YEAR_HALF" NUMBER(8),
	"YEAR" NUMBER(8)
)
;