-- dim_PRODUCT
execute bl_cl.PKG_DROP.DROP_Proc('"DWH"."DIM_PRODUCTS"','table');
CREATE TABLE "DWH"."DIM_PRODUCTS"
(
  "PRODUCT_SURR_ID" NUMBER(8),
	"PRODUCT_ID" NUMBER(8),
	"PRODUCT_DESC" VARCHAR2(50),
	"PRODUCT_PRICE" VARCHAR2(50),
	"CATEGORY_ID" NUMBER(8),
	"CATEGORY_DESC" VARCHAR2(50),
	"SUBCATEGORY_ID" VARCHAR2(50),
	"SUBCATEGORY_DESC" VARCHAR2(50),
	"SUBCATEGORY_SIZE" NUMBER(8,2),
	"SUBCATEGORY_TOBACCO" NUMBER(8,2),
	"LOCALIZATION_ID" NUMBER(8),
	"LOCALIZATION_DESC" VARCHAR2(50),
	"UPDATE_DT" DATE,
	"INSERT_DT" DATE
)
;

execute bl_cl.pkg_drop.DROP_proc('seq_dproduct','sequence');
CREATE SEQUENCE seq_dproduct
      INCREMENT BY 1 
          START WITH 1 
       MINVALUE 1 
        NOCYCLE; 
