-- dim_DEPARTMENTS
execute bl_cl.PKG_DROP.DROP_Proc('"DWH"."DIM_DEPARTMENTS"','table');
CREATE TABLE "DWH"."DIM_DEPARTMENTS"
(
  "DEPARTMENT_SURR_ID" NUMBER(15),
	"DEPARTMENT_ID" NUMBER(8),
	"DEPARTMENT_DESC" VARCHAR2(50),
	"ADDRESS_ID" VARCHAR2(50),
	"ADDRESS_DESC" VARCHAR2(50),
	"CITY_ID" VARCHAR2(50),
	"CITY_DESC" VARCHAR2(100),
	"COUNTRY_ID" VARCHAR2(50),
	"COUNTRY_DESC" VARCHAR2(100),
	"SUBREGION_ID" NUMBER(8),
	"SUBREGION_DESC" VARCHAR2(50),
	"REGION_ID" VARCHAR2(50),
	"REGION_DESC" VARCHAR2(50),
  "PHONE" VARCHAR2(20),
	"POSTAL_CODE" VARCHAR2(50),
	"START_DT" DATE,
	"END_DT" DATE,
	"IS_ACTIVE" VARCHAR2(1),
	"UPDATE_DT" DATE,
	"INSERT_DT" DATE
)
;

execute bl_cl.pkg_drop.DROP_proc('seq_ddepartments','sequence');
CREATE SEQUENCE seq_ddepartments
      INCREMENT BY 1 
          START WITH 1 
       MINVALUE 1 
        NOCYCLE; 