execute bl_cl.PKG_DROP.DROP_Proc('"DWH"."DIM_CONSUMERS"','table');
CREATE TABLE "DWH"."DIM_CONSUMERS"
(
  "CONSUMER_SURR_ID" NUMBER(15),
	"CONSUMER_ID" NUMBER(15),
	"CONSUMER_DESC" VARCHAR2(100),
	"RATE_ID" NUMBER(8),
	"RATE_DESC" VARCHAR2(50),
	"RESPONSIBLE_ID" NUMBER(15),
	"RESPONSIBLE_DESC" VARCHAR2(100),
	"ADDRESS_ID" NUMBER(15),
	"ADDRESS_DESC" VARCHAR2(100),
	"CITY_ID" NUMBER(15),
  "CITY_DESC" VARCHAR2(100),
	"COUNTRY_ID" NUMBER(8),
  "COUNTRY_DESC" VARCHAR2(100),
	"SUBREGION_ID" NUMBER(8),
	"SUBREGION_DESC" VARCHAR2(100),
	"REGION_ID" NUMBER(8),
	"REGION_DESC" VARCHAR2(100),
	"POSTAL_CODE" VARCHAR2(50),
	"PHONE" VARCHAR2(50),
  "UPDATE_DT" DATE,
	"INSERT_DT" DATE
)
;

execute bl_cl.pkg_drop.DROP_proc('seq_dconsumers','sequence');
CREATE SEQUENCE seq_dconsumers
      INCREMENT BY 1 
          START WITH 1 
       MINVALUE 1 
        NOCYCLE; 