CREATE OR REPLACE PUBLIC SYNONYM DIM_CONSUMERS FOR "DWH"."DIM_CONSUMERS"; 
CREATE OR REPLACE PUBLIC SYNONYM DIM_DEPARTMENTS FOR "DWH"."DIM_DEPARTMENTS"; 
CREATE OR REPLACE PUBLIC SYNONYM DIM_DATE FOR "DWH"."DIM_DATE"; 
CREATE OR REPLACE PUBLIC SYNONYM DIM_PRODUCTS FOR "DWH"."DIM_PRODUCTS"; 
CREATE OR REPLACE PUBLIC SYNONYM DIM_PROMOTIONS FOR "DWH"."DIM_PROMOTIONS"; 
CREATE OR REPLACE PUBLIC SYNONYM FCT_SALES FOR "DWH"."FCT_SALES"; 