execute bl_cl.PKG_DROP.DROP_Proc('"DWH"."FCT_SALES"','table');
CREATE TABLE "DWH"."FCT_SALES"
(
	"PRODUCT_ID" NUMBER(8) NOT NULL,
	"DEPARTMENT_ID" NUMBER(8) NOT NULL,
	"CONSUMER_ID" NUMBER(8) NOT NULL,
	"PROMO_ID" NUMBER(8) NOT NULL,
	"DATE_ID" DATE,
	"COST" NUMBER(8,2),
	"AMOUNT" NUMBER(8,2),
  "UPDATE_DT" DATE,
	"INSERT_DT" DATE
)
;