CREATE USER dwh IDENTIFIED BY 123456;
GRANT SELECT ON DIM_CONSUMERS TO bl_3nf;
GRANT SELECT ON DIM_DEPARTMENTS TO bl_3nf;
GRANT SELECT ON DIM_DATE TO bl_3nf;
GRANT SELECT ON DIM_PRODUCTS TO bl_3nf;
GRANT SELECT ON DIM_PROMOTIONS TO bl_3nf;
GRANT SELECT ON FCT_SALES TO bl_3nf;