DROP TABLE DIM_CUSTOMERS CASCADE CONSTRAINTS;
CREATE TABLE DIM_CUSTOMERS(
    CUSTOMER_ID	        NUMBER NOT NULL,
    CUSTOMER_NAME	    VARCHAR2(200) NOT NULL,
    CUSTOMER_SURNAME	VARCHAR2(200) NOT NULL,	
    AGE	                NUMBER(8) NOT NULL,	
    GENDER	            NUMBER(8) NOT NULL,
    PHONE	            VARCHAR2(200) NOT NULL,	
    EMAIL	            VARCHAR2(200) NOT NULL,
    INSERT_DT           DATE          NOT NULL,
    UPDATE_DT           DATE          NOT NULL,
    CONSTRAINT CUSTOMER_ID PRIMARY KEY (CUSTOMER_ID));