CREATE TABLE PARTITIONS (
    ID   NUMBER NOT NULL,
    data_part DATE)
    
PARTITION BY RANGE ( data_part ) (
PARTITION BEFORE2013
VALUES LESS THAN ( TO_DATE('01.01.2013','dd.mm.yyyy') ),
PARTITION BEFORE2014
VALUES LESS THAN ( TO_DATE('01.01.2014','dd.mm.yyyy') ),
PARTITION BEFORE2015
VALUES LESS THAN ( TO_DATE('01.01.2015','dd.mm.yyyy') ),
PARTITION BEFORE2016
VALUES LESS THAN ( TO_DATE('01.01.2016','dd.mm.yyyy') ),
PARTITION BEFORE2017
VALUES LESS THAN ( TO_DATE('01.01.2017','dd.mm.yyyy') ),
PARTITION LESS_MAX
VALUES LESS THAN ( MAXVALUE ));

CREATE SEQUENCE seq
START WITH 1
INCREMENT BY 1;
  
INSERT INTO  PARTITIONS 
SELECT seq.nextval, SYSDATE+rownum-365*5   
FROM dual
CONNECT BY rownum <=365*5;

ALTER TABLE PARTITIONS DROP PARTITION LESS_MAX;
ALTER TABLE PARTITIONS DROP PARTITION BEFORE2017;

ALTER TABLE PARTITIONS 
ADD PARTITION BEFORE2017 VALUES LESS THAN (to_date('01.01.2017','dd.mm.yyyy'));

ALTER TABLE PARTITIONS 
MERGE PARTITIONS BEFORE2015, BEFORE2016 into partition PART_LESS_2016;

ALTER TABLE PARTITIONS MOVE PARTITION BEFORE2013
TABLESPACE users NOLOGGING COMPRESS;

ALTER TABLE PARTITIONS SPLIT PARTITION BEFORE2016 
AT (to_date('01-01-2015', 'DD-MM-YYYY')) INTO (partition BEFORE2015, partition BEFORE2016);

ALTER TABLE PARTITIONS TRUNCATE PARTITION BEFORE2014;

CREATE TABLE PARTITIONS_HASH (
    ID   NUMBER NOT NULL,
    data_part DATE)
    
    PARTITION BY HASH ( data_part ) (
        PARTITION BEFORE2013,
        PARTITION BEFORE2014,
        PARTITION BEFORE2015,
        PARTITION BEFORE2016,
        PARTITION BEFORE2017,
        PARTITION LESS_MAX);

ALTER TABLE PARTITIONS_HASH COALESCE PARTITION;