CREATE TABLE BL_DWH_CUSTOMERS (
    ID_CUSTOMER NUMBER(25),
    CUSTOMER_KEY NUMBER(25),
    FIRST_NAME VARCHAR2(70),
    LAST_NAME VARCHAR2(70),
    MOBILE_PHONE NUMBER(20),
    ADDRESS VARCHAR2(100),
    LOCATION VARCHAR2(300),
    START_DT DATE,
    END_DT DATE
    );
    

CREATE TABLE BL_DWH_EMPLOYEES (
    ID_EMPLOYEE NUMBER(25),
    EMPLOYEE_KEY NUMBER(25),
    FIRST_NAME VARCHAR2(70),
    LAST_NAME VARCHAR2(70),
    JOB_NAME VARCHAR2(50),
    SALARY NUMBER(15),
    MANAGER_ID NUMBER(25),
    MOBILE_PHONE NUMBER(20),
    ADDRESS VARCHAR2(100),
    LOCATION VARCHAR2(300),
    START_DT DATE,
    END_DT DATE
    );


CREATE TABLE BL_DWH_STORES (
    ID_STORE NUMBER(10),
    STORE_KEY NUMBER(10),
    STORE_DESC VARCHAR2(500),
    PHONE NUMBER(15),
    ADDRESS VARCHAR2(250),
    LOCATION VARCHAR2(350),
    ID_MANAGER NUMBER(25),
    MANAGER_NAME VARCHAR2(150)
    );


CREATE TABLE BL_DWH_PRODUCTS (
    ID_PRODUCT NUMBER(15),
    PRODUCT_KEY NUMBER(15),
    PRODUCT_NAME VARCHAR2(100),
    PRODUCS_COST NUMBER(25),
    SUBCATEGORY_NAME VARCHAR2(100),
    CATEGORY_NAME VARCHAR2(100),
    PRODUCT_DESC VARCHAR2(3000),
    SUBCATEGORY_DESC VARCHAR2(750),
    CATEGORY_DESC VARCHAR2(500)
    );
    
    

CREATE TABLE  BL_DWH_FACTSSALES (
    ID_SALES NUMBER(30),
    SALES_KEY NUMBER(30),
    ID_CUSTOMER NUMBER(25),
    ID_EMPLOYEE NUMBER(15),
    ID_STORE NUMBER(15),
    ID_PRODUCT NUMBER(15),
    ID_DATE DATE NOT NULL,
    TIME_SALE TIMESTAMP NOT NULL,
    AMOUNT NUMBER(15)
    );
    
    
    
    
  