CREATE TABLE FactSales
  (
    Event_dt            DATE NOT NULL,
    Customer_key        NUMBER(8) NOT NULL,
    Employee_key        NUMBER(8) NOT NULL,
    Store_key           NUMBER(8) NOT NULL,
    Product_key         NUMBER(8) NOT NULL,
    Discount_key        NUMBER(8) NOT NULL,
    Payment_key         NUMBER(8) NOT NULL,
    Check_id            NUMBER(8) NOT NULL,
    Quantity            NUMBER(5) NOT NULL,
    Unit_price_BYN      NUMBER(10,2) NOT NULL,
    Unit_price_disc_BYN NUMBER(10,2) NOT NULL,
    Sales_Amount_BYN    NUMBER(10,2) NOT NULL,
    BYN_USD             NUMBER(8,3) NOT NULL,
    Unit_price_USD      NUMBER(10,2) NOT NULL,
    Unit_price_disc_USD NUMBER(10,2) NOT NULL,
    Sales_Amount_USD    NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_date FOREIGN KEY (Event_dt) REFERENCES dimdate(full_date_dt),
    CONSTRAINT fk_customer FOREIGN KEY (customer_key) REFERENCES dimcustomer(customer_key),
    CONSTRAINT fk_employee FOREIGN KEY (employee_key) REFERENCES dimemployee_scd(employee_key),
    CONSTRAINT fk_store FOREIGN KEY (store_key) REFERENCES dimstore(store_key),
    CONSTRAINT fk_product FOREIGN KEY (product_key) REFERENCES dimproduct(product_key),
    CONSTRAINT fk_payment FOREIGN KEY (payment_key) REFERENCES dimpayment(payment_key),
    CONSTRAINT fk_discount FOREIGN KEY (discount_key) REFERENCES dimdiscount_scd(discount_key)
  );
