CREATE TABLE PRODUCTS
  ( PRODUCT_ID   NUMBER PRIMARY KEY,
    PRODUCT_CODE VARCHAR2 (8) ,
    PRODUCT_NAME VARCHAR2 (100) ,
    BRAND_ID     NUMBER ,
    CATEGORY_ID  NUMBER
  ) ;
  
--TRUNCATE TABLE PRODUCTS;

INSERT INTO PRODUCTS( PRODUCT_ID, PRODUCT_CODE, PRODUCT_NAME, BRAND_ID, CATEGORY_ID)
SELECT
    ROWNUM AS PRODUCT_ID,
    DBMS_RANDOM.STRING('U',DBMS_RANDOM.VALUE(8,8)) AS PRODUCT_CODE,
    E.LAST_NAME AS PRODUCT_NAME,
    ROUND(DBMS_RANDOM.VALUE ( 1, (SELECT MAX(BRAND_ID)FROM BRANDS))) AS BRAND_ID,
    ROUND(DBMS_RANDOM.VALUE ( 1, (SELECT MAX(CATEGORY_ID)FROM CATEGORIES))) AS CATEGORY_ID
    FROM HR.EMPLOYEES E,
    BRANDS B,
    CATEGORIES C
  , ( SELECT LEVEL FROM DUAL CONNECT BY LEVEL <= 10);

COMMIT;

SELECT * FROM PRODUCTS;
  
  