DROP TABLE DIM_STORES CASCADE CONSTRAINTS;
CREATE TABLE DIM_STORES(
    STORE_ID        NUMBER NOT NULL,
    STORE_NAME	    VARCHAR2(200) NOT NULL,	
    PHONE	        VARCHAR2(200) NOT NULL,	
    EMAIL	        VARCHAR2(200) NOT NULL,
    STREET_NAME     VARCHAR2(200) NOT NULL,
    HOUSE_NUMBER    VARCHAR2(200) NOT NULL,	
    CITY_NAME       VARCHAR2(200) NOT NULL,
    COUNTRY_NAME    VARCHAR2(200) NOT NULL,
    INSERT_DT       DATE          NOT NULL,
    UPDATE_DT       DATE          NOT NULL,
    CONSTRAINT STORE_ID PRIMARY KEY (STORE_ID));