DROP TABLE "DIM_Customers_SCD" CASCADE CONSTRAINTS
;

DROP TABLE "DIM_PayDeliveries" CASCADE CONSTRAINTS
;

DROP TABLE "DIM_Points" CASCADE CONSTRAINTS
;

DROP TABLE "DIM_Products_SCD" CASCADE CONSTRAINTS
;

DROP TABLE "DIM_Time_Day" CASCADE CONSTRAINTS
;

DROP TABLE "FCT_SalesItems" CASCADE CONSTRAINTS
;

CREATE TABLE "DIM_Customers_SCD"
(
	"CUSTOMER_SURR_ID" NUMBER(8) NOT NULL,
	"CUSTOMER_SRC_ID" NUMBER(8),
	"CUSTOMER_CODE" NUMBER(7),
	"CUSTOMER_LAST_NAME" VARCHAR2(50),
	"CUSTOMER_FIRST_NAME" VARCHAR2(50),
	"CUSTOMER_MIDDLE_NAME" VARCHAR2(50),
	"CUSTOMER_AGE" VARCHAR2(3),
	"CUSTOMER_GENDER" VARCHAR2(1),
	"CUSTOMER_PERSONAL_DISCOUNT" NUMBER(2),
	"CUSTOMER_LOCATION_TYPE" VARCHAR2(50),
	"CUSTOMER_LOCATION" VARCHAR2(50),
	"CUSTOMER_DISTRICT" VARCHAR2(50),
	"CUSTOMER_REGION" VARCHAR2(50),
	"CUSTOMER_START_DT" DATE,
	"CUSTOMER_END_DT" DATE,
	"CUSTOMER_IS_ACTIVE" VARCHAR2(1),
	"INSERT_DT" DATE
)
;

CREATE TABLE "DIM_PayDeliveries"
(
	"PAYDELIVERY_SURR_ID" NUMBER(2) NOT NULL,
	"DELIVERY_SRC_ID" NUMBER(8),
	"DELIVERY_DESC" VARCHAR2(50),
	"PAYOPTION_SRC_ID" NUMBER(3),
	"PAYOPTION_DESC" VARCHAR2(50),
	"INSERT_DT" DATE
)
;

CREATE TABLE "DIM_Points"
(
	"POINT_SURR_ID" NUMBER(3) NOT NULL,
	"POINT_SRC_ID" NUMBER(3),
	"POINT_CODE" VARCHAR2(3),
	"POINT_LOCATION" VARCHAR2(50),
	"POINT_REGION" VARCHAR2(50),
	"POINT_DISTRICT" VARCHAR2(50),
	"INSERT_DT" DATE
)
;

CREATE TABLE "DIM_Products_SCD"
(
	"PRODUCT_SURR_ID" NUMBER(8) NOT NULL,
	"PRODUCT_SRC_ID" NUMBER(8),
	"PRODUCT_CODE" NUMBER(9),
	"PRODUCT_DESC" VARCHAR2(50),
	"PRODUCT_VENDORCODE" NUMBER(8),
	"PRODUCT_COLOR" VARCHAR2(25),
	"PRODUCT_BRAND" VARCHAR2(100),
	"PRODUCT_TYPE" VARCHAR2(100),
	"PRODUCT_SUBCATEGORY" VARCHAR2(150),
	"PRODUCT_CATEGORY" VARCHAR2(50),
	"PRODUCT_START_DT" DATE,
	"PRODUCT_END_DT" DATE,
	"PRODUCT_IS_ACTIVE" VARCHAR2(1),
	"INSERT_DT" DATE
)
;

CREATE TABLE "DIM_Time_Day"
(
	"FULL_DATE" DATE NOT NULL,
	"DAY_WEEK" NUMBER(1),
	"DAY_WEEK_DECS" VARCHAR2(50),
	"DAY_MONTH" NUMBER(2),
	"DAY_YEAR" NUMBER(3),
	"MONTH_NUM" NUMBER(2),
	"MONTH_DESC" VARCHAR2(50),
	"MONTH_YEAR" VARCHAR2(7),
	"QUARTER" NUMBER(1),
	"QUARTER_YEAR" VARCHAR2(6),
	"HALF_YEAR" NUMBER(1),
	"HALF_YEAR_YEAR" VARCHAR2(6),
	"YEAR" NUMBER(4),
	"INSERT_DT" DATE
)
;

CREATE TABLE "FCT_SalesItems"
(
	"DIM_ORDERDATE" DATE NOT NULL,
	"DD_ORDER_ID" NUMBER(10,2),
	"DIM_CUSTOMER_ID" NUMBER(8) NOT NULL,
	"DIM_PAYDATE" DATE NOT NULL,
	"DIM_PRODUCT_ID" NUMBER(8) NOT NULL,
	"DIM_PAYDELIVERY_ID" NUMBER(2) NOT NULL,
	"DIM_POINT_ID" NUMBER(3),
	"FCT_QUANTITY" NUMBER(10),
	"FCT_ITEM_SUM" NUMBER(35,2),
	"FCT_DISCOUNT_SUM" NUMBER(35,2),
	"FCT_TOTAL_SUM" NUMBER(35,2),
	"INSERT_DT" DATE
)
;

ALTER TABLE "DIM_Customers_SCD" 
 ADD CONSTRAINT "PK_CUSTOMERS"
	PRIMARY KEY ("CUSTOMER_SURR_ID") USING INDEX
;

ALTER TABLE "DIM_Customers_SCD" 
 ADD CONSTRAINT "UK_CUSTOMER_CODE" UNIQUE ("CUSTOMER_CODE") USING INDEX
;

ALTER TABLE "DIM_PayDeliveries" 
 ADD CONSTRAINT "PK_PAYDELIVERIES"
	PRIMARY KEY ("PAYDELIVERY_SURR_ID") USING INDEX
;

ALTER TABLE "DIM_Points" 
 ADD CONSTRAINT "PK_POINTS"
	PRIMARY KEY ("POINT_SURR_ID") USING INDEX
;

ALTER TABLE "DIM_Products_SCD" 
 ADD CONSTRAINT "PK_PRODUCTS"
	PRIMARY KEY ("PRODUCT_SURR_ID") USING INDEX
;

ALTER TABLE "DIM_Products_SCD" 
 ADD CONSTRAINT "UK_CODE" UNIQUE ("PRODUCT_CODE") USING INDEX
;

ALTER TABLE "DIM_Time_Day" 
 ADD CONSTRAINT "PK_TIME_DAY"
	PRIMARY KEY ("FULL_DATE") USING INDEX
;

ALTER TABLE "FCT_SalesItems" 
 ADD CONSTRAINT "PK_FCT_SALESITEMS"
	PRIMARY KEY ("DIM_CUSTOMER_ID","DIM_PAYDATE","DIM_PRODUCT_ID","DIM_PAYDELIVERY_ID","DIM_ORDERDATE") USING INDEX
;

ALTER TABLE "FCT_SalesItems" 
 ADD CONSTRAINT "FK_FCT_SALESITEMS_CUSTOMERS"
	FOREIGN KEY ("DIM_CUSTOMER_ID") REFERENCES "DIM_Customers_SCD" ("CUSTOMER_SURR_ID")
;

ALTER TABLE "FCT_SalesItems" 
 ADD CONSTRAINT "FK_FCT_SALESITEMS_DIM_TIME_D01"
	FOREIGN KEY ("DIM_ORDERDATE") REFERENCES "DIM_Time_Day" ("FULL_DATE")
;

ALTER TABLE "FCT_SalesItems" 
 ADD CONSTRAINT "FK_FCT_SALESITEMS_DIM_TIME_D02 "
	FOREIGN KEY ("DIM_PAYDATE") REFERENCES "DIM_Time_Day" ("FULL_DATE")
;

ALTER TABLE "FCT_SalesItems" 
 ADD CONSTRAINT "FK_FCT_SALESITEMS_PAYDELIVERIES"
	FOREIGN KEY ("DIM_PAYDELIVERY_ID") REFERENCES "DIM_PayDeliveries" ("PAYDELIVERY_SURR_ID")
;

ALTER TABLE "FCT_SalesItems" 
 ADD CONSTRAINT "FK_FCT_SALESITEMS_POINTS"
	FOREIGN KEY ("DIM_POINT_ID") REFERENCES "DIM_Points" ("POINT_SURR_ID")
;

ALTER TABLE "FCT_SalesItems" 
 ADD CONSTRAINT "FK_FCT_SALESITEMS_PRODUCT"
	FOREIGN KEY ("DIM_PRODUCT_ID") REFERENCES "DIM_Products_SCD" ("PRODUCT_SURR_ID")
;
