CREATE TABLE CE_SUPPLIER
  (
    SUPPLIER_SRCID NUMBER (8)        NOT NULL,
    SUPPLIER_NAME  VARCHAR2 (100)     NOT NULL,
    PHONE          VARCHAR2 (50)        NOT NULL,
    EMAIL          VARCHAR2 (100)     NOT NULL,
    ADDRESS_SRCID  NUMBER (8)        NOT NULL,
    START_DT       DATE              NOT NULL,
    END_DT         DATE              NOT NULL,
    IS_ACTIVE      VARCHAR2 (20)      NOT NULL,
    CONSTRAINT "PK_SUPPLIER_SRCID" PRIMARY KEY (SUPPLIER_SRCID),
    CONSTRAINT "FK2_ADDRESS_SRCID" FOREIGN KEY(ADDRESS_SRCID) REFERENCES CE_ADDRESS (ADDRESS_SRCID)
  );