CREATE TABLE CE_ATE
  (
    ATE_SRCID     NUMBER (8)         NOT NULL,
    ATE_NAME      VARCHAR2 (40)      NOT NULL,
    COUNTRY_SRCID NUMBER (8)         NOT NULL,
    CONSTRAINT "PK_ATE_SRCID" PRIMARY KEY (ATE_SRCID),
    CONSTRAINT "FK_COUNTRY_SRCID" FOREIGN KEY (COUNTRY_SRCID) REFERENCES CE_COUNTRY(COUNTRY_SRCID)
  );