--------------------------------------------------------
--  DDL for Table DIM_SUPPLIER_SCD
--------------------------------------------------------

  CREATE TABLE "BL_DM"."DIM_SUPPLIER_SCD" 
   (	"SUP_SURR_ID" NUMBER(8,0), 
	"SUP_ID" NUMBER(8,0), 
	"SUP_NAME" VARCHAR2(50 BYTE), 
	"PHONE" NUMBER(8,0), 
	"E_MAIL" VARCHAR2(50 BYTE), 
	"ADDRESS" VARCHAR2(50 BYTE), 
	"CITY" VARCHAR2(50 BYTE), 
	"ATE" VARCHAR2(50 BYTE), 
	"COUNTRY" VARCHAR2(50 BYTE), 
	"START_DT" DATE, 
	"END_DT" DATE, 
	"IS_ACTIVE" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBS_PDB_BL_DM" ;
--------------------------------------------------------
--  DDL for Index PK_SUPPLIER_SURR_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "BL_DM"."PK_SUPPLIER_SURR_ID" ON "BL_DM"."DIM_SUPPLIER_SCD" ("SUP_SURR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "TBS_PDB_BL_DM" ;
--------------------------------------------------------
--  Constraints for Table DIM_SUPPLIER_SCD
--------------------------------------------------------

  ALTER TABLE "BL_DM"."DIM_SUPPLIER_SCD" MODIFY ("SUP_SURR_ID" NOT NULL ENABLE);
  ALTER TABLE "BL_DM"."DIM_SUPPLIER_SCD" MODIFY ("SUP_ID" NOT NULL ENABLE);
  ALTER TABLE "BL_DM"."DIM_SUPPLIER_SCD" MODIFY ("SUP_NAME" NOT NULL ENABLE);
  ALTER TABLE "BL_DM"."DIM_SUPPLIER_SCD" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "BL_DM"."DIM_SUPPLIER_SCD" MODIFY ("E_MAIL" NOT NULL ENABLE);
  ALTER TABLE "BL_DM"."DIM_SUPPLIER_SCD" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "BL_DM"."DIM_SUPPLIER_SCD" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "BL_DM"."DIM_SUPPLIER_SCD" MODIFY ("ATE" NOT NULL ENABLE);
  ALTER TABLE "BL_DM"."DIM_SUPPLIER_SCD" MODIFY ("COUNTRY" NOT NULL ENABLE);
  ALTER TABLE "BL_DM"."DIM_SUPPLIER_SCD" MODIFY ("START_DT" NOT NULL ENABLE);
  ALTER TABLE "BL_DM"."DIM_SUPPLIER_SCD" MODIFY ("END_DT" NOT NULL ENABLE);
  ALTER TABLE "BL_DM"."DIM_SUPPLIER_SCD" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "BL_DM"."DIM_SUPPLIER_SCD" ADD CONSTRAINT "PK_SUPPLIER_SURR_ID" PRIMARY KEY ("SUP_SURR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "TBS_PDB_BL_DM"  ENABLE;
