--------------------------------------------------------
--  DDL for Table DIM_PAYMENT
--------------------------------------------------------

  CREATE TABLE "BL_DM"."DIM_PAYMENT" 
   (	"PAYMENT_ID" NUMBER(8,0), 
	"PAYMENT_TYPE" VARCHAR2(20 BYTE), 
	"START_DT" DATE, 
	"END_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_PDB_BL_DM" ;
--------------------------------------------------------
--  DDL for Index PK_PAYMENT_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "BL_DM"."PK_PAYMENT_ID" ON "BL_DM"."DIM_PAYMENT" ("PAYMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_PDB_BL_DM" ;
--------------------------------------------------------
--  Constraints for Table DIM_PAYMENT
--------------------------------------------------------

  ALTER TABLE "BL_DM"."DIM_PAYMENT" MODIFY ("PAYMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "BL_DM"."DIM_PAYMENT" MODIFY ("PAYMENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "BL_DM"."DIM_PAYMENT" MODIFY ("START_DT" NOT NULL ENABLE);
  ALTER TABLE "BL_DM"."DIM_PAYMENT" MODIFY ("END_DT" NOT NULL ENABLE);
  ALTER TABLE "BL_DM"."DIM_PAYMENT" ADD CONSTRAINT "PK_PAYMENT_ID" PRIMARY KEY ("PAYMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_PDB_BL_DM"  ENABLE;
