--------------------------------------------------------
--  File created - Sunday-December-03-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DIM_CUSTOMER
--------------------------------------------------------

  CREATE TABLE "BL_DM"."DIM_CUSTOMER" 
   (	"CUST_ID" NUMBER(8,0), 
	"LAST_NAME" VARCHAR2(100 BYTE), 
	"FIRST_NAME" VARCHAR2(100 BYTE), 
	"MIDDLE_NAME" VARCHAR2(100 BYTE), 
	"AGE" VARCHAR2(10 BYTE), 
	"GENDER" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PHONE" VARCHAR2(100 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"CITY" VARCHAR2(100 BYTE), 
	"ATE" VARCHAR2(100 BYTE), 
	"COUNTRY" VARCHAR2(100 BYTE), 
	"START_DT" DATE, 
	"END_DT" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBS_PDB_BL_DM" ;
--------------------------------------------------------
--  DDL for Index PK_CUSTOMER_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "BL_DM"."PK_CUSTOMER_ID" ON "BL_DM"."DIM_CUSTOMER" ("CUST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "TBS_PDB_BL_DM" ;
--------------------------------------------------------
--  Constraints for Table DIM_CUSTOMER
--------------------------------------------------------

  ALTER TABLE "BL_DM"."DIM_CUSTOMER" MODIFY ("CUST_ID" NOT NULL ENABLE);
  ALTER TABLE "BL_DM"."DIM_CUSTOMER" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "BL_DM"."DIM_CUSTOMER" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "BL_DM"."DIM_CUSTOMER" MODIFY ("MIDDLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "BL_DM"."DIM_CUSTOMER" MODIFY ("AGE" NOT NULL ENABLE);
  ALTER TABLE "BL_DM"."DIM_CUSTOMER" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "BL_DM"."DIM_CUSTOMER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "BL_DM"."DIM_CUSTOMER" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "BL_DM"."DIM_CUSTOMER" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "BL_DM"."DIM_CUSTOMER" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "BL_DM"."DIM_CUSTOMER" MODIFY ("ATE" NOT NULL ENABLE);
  ALTER TABLE "BL_DM"."DIM_CUSTOMER" MODIFY ("COUNTRY" NOT NULL ENABLE);
  ALTER TABLE "BL_DM"."DIM_CUSTOMER" MODIFY ("START_DT" NOT NULL ENABLE);
  ALTER TABLE "BL_DM"."DIM_CUSTOMER" MODIFY ("END_DT" NOT NULL ENABLE);
  ALTER TABLE "BL_DM"."DIM_CUSTOMER" ADD CONSTRAINT "PK_CUSTOMER_ID" PRIMARY KEY ("CUST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "TBS_PDB_BL_DM"  ENABLE;
