--------------------------------------------------------
--  File created - Monday-December-04-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADDRESS
--------------------------------------------------------

  CREATE TABLE "BL_3NF"."ADDRESS" 
   (	"ID_ADDRESS" NUMBER(20,0), 
	"STREET" VARCHAR2(50 BYTE), 
	"HOUSE" NUMBER(5,0), 
	"FLAT" NUMBER(5,0), 
	"PHONE" VARCHAR2(30 BYTE), 
	"CITY_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CATEGORY
--------------------------------------------------------

  CREATE TABLE "BL_3NF"."CATEGORY" 
   (	"ID_CATEGORY" NUMBER(7,0), 
	"CATEGORY_NAME" VARCHAR2(100 BYTE), 
	"CATEGORY_DESC" VARCHAR2(750 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CITIES
--------------------------------------------------------

  CREATE TABLE "BL_3NF"."CITIES" 
   (	"ID_CITY" NUMBER(10,0), 
	"CITY_NAME" VARCHAR2(50 BYTE), 
	"ID_COUNTRY" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CONTINENTS
--------------------------------------------------------

  CREATE TABLE "BL_3NF"."CONTINENTS" 
   (	"ID_CONTINENT" NUMBER(3,0), 
	"CONTINENT_NAME" VARCHAR2(70 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COUNTRIES
--------------------------------------------------------

  CREATE TABLE "BL_3NF"."COUNTRIES" 
   (	"ID_COUNTRY" NUMBER(10,0), 
	"COUNTRY_NAME" VARCHAR2(70 BYTE), 
	"COUNTRY_CODE" VARCHAR2(5 BYTE), 
	"ID_REGION" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CUSTOMERS
--------------------------------------------------------

  CREATE TABLE "BL_3NF"."CUSTOMERS" 
   (	"ID_CUSTOMER" NUMBER(15,0), 
	"ID_B" NUMBER(15,0), 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"LAST_NAME" VARCHAR2(70 BYTE), 
	"MOBILE_PHONE" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(70 BYTE), 
	"ID_ADDRESS" NUMBER(20,0), 
	"START_DT" DATE, 
	"END_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEES
--------------------------------------------------------

  CREATE TABLE "BL_3NF"."EMPLOYEES" 
   (	"ID_EMP" NUMBER(10,0), 
	"ID_EMPLOYEE" NUMBER(15,0), 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"LAST_NAME" VARCHAR2(70 BYTE), 
	"MOBILE_PHONE" VARCHAR2(30 BYTE), 
	"ID_STORE" NUMBER(10,0), 
	"ID_JOB" NUMBER(5,0), 
	"SALARY" NUMBER(10,0), 
	"MANAGER_ID" NUMBER(10,0), 
	"ID_ADDRESS" NUMBER(20,0), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"START_DT" DATE, 
	"END_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table JOBS
--------------------------------------------------------

  CREATE TABLE "BL_3NF"."JOBS" 
   (	"ID_JOBS" NUMBER(5,0), 
	"JOB_NAME" VARCHAR2(50 BYTE), 
	"JOB_DESC" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PAYMENTS
--------------------------------------------------------

  CREATE TABLE "BL_3NF"."PAYMENTS" 
   (	"ID_PAYMENT" NUMBER(25,0), 
	"PAYMENT_KEY" NUMBER(25,0), 
	"ID_SALES" NUMBER(25,0), 
	"ID_PRODUCT" NUMBER(15,0), 
	"AMOUNT" NUMBER(15,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "BL_3NF"."PRODUCTS" 
   (	"ID_PRODUCT" NUMBER(15,0), 
	"PRODUCT_KEY" NUMBER(15,0), 
	"PRODUCT_NAME" VARCHAR2(100 BYTE), 
	"PRODUCT_DESC" VARCHAR2(3000 BYTE), 
	"ID_SUBCATEGORY" NUMBER(10,0), 
	"PROD_COST" NUMBER(15,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REGIONS
--------------------------------------------------------

  CREATE TABLE "BL_3NF"."REGIONS" 
   (	"ID_REGION" NUMBER(3,0), 
	"REGION_NAME" VARCHAR2(70 BYTE), 
	"ID_CONTINENT" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SALES
--------------------------------------------------------

  CREATE TABLE "BL_3NF"."SALES" 
   (	"ID_SALES" NUMBER(25,0), 
	"SALES_KEY" NUMBER(25,0), 
	"ID_CUSTOMER" NUMBER(15,0), 
	"ID_EMPLOYEE" NUMBER(10,0), 
	"ID_STORE" NUMBER(10,0), 
	"DATE_SALES" DATE, 
	"TIME_SALES" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STORES
--------------------------------------------------------

  CREATE TABLE "BL_3NF"."STORES" 
   (	"ID_STORES" NUMBER(10,0), 
	"STORE_KEY" NUMBER(10,0), 
	"STORES_DESC" VARCHAR2(250 BYTE), 
	"ID_ADDRESS" NUMBER(20,0), 
	"ID_MANAGAER" NUMBER(20,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SUBCATEGORY
--------------------------------------------------------

  CREATE TABLE "BL_3NF"."SUBCATEGORY" 
   (	"ID_SUBCATEGORY" NUMBER(10,0), 
	"SUBCATEGORY_NAME" VARCHAR2(100 BYTE), 
	"SUBCATEGORY_DESC" VARCHAR2(750 BYTE), 
	"ID_CATEGORY" NUMBER(7,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0013422
--------------------------------------------------------

  CREATE UNIQUE INDEX "BL_3NF"."SYS_C0013422" ON "BL_3NF"."ADDRESS" ("ID_ADDRESS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0013458
--------------------------------------------------------

  CREATE UNIQUE INDEX "BL_3NF"."SYS_C0013458" ON "BL_3NF"."CATEGORY" ("ID_CATEGORY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0013417
--------------------------------------------------------

  CREATE UNIQUE INDEX "BL_3NF"."SYS_C0013417" ON "BL_3NF"."CITIES" ("ID_CITY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0013400
--------------------------------------------------------

  CREATE UNIQUE INDEX "BL_3NF"."SYS_C0013400" ON "BL_3NF"."CONTINENTS" ("ID_CONTINENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0013409
--------------------------------------------------------

  CREATE UNIQUE INDEX "BL_3NF"."SYS_C0013409" ON "BL_3NF"."COUNTRIES" ("ID_COUNTRY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0013439
--------------------------------------------------------

  CREATE UNIQUE INDEX "BL_3NF"."SYS_C0013439" ON "BL_3NF"."CUSTOMERS" ("ID_CUSTOMER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0013449
--------------------------------------------------------

  CREATE UNIQUE INDEX "BL_3NF"."SYS_C0013449" ON "BL_3NF"."EMPLOYEES" ("ID_EMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0013441
--------------------------------------------------------

  CREATE UNIQUE INDEX "BL_3NF"."SYS_C0013441" ON "BL_3NF"."JOBS" ("ID_JOBS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0013771
--------------------------------------------------------

  CREATE UNIQUE INDEX "BL_3NF"."SYS_C0013771" ON "BL_3NF"."PAYMENTS" ("ID_PAYMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0013478
--------------------------------------------------------

  CREATE UNIQUE INDEX "BL_3NF"."SYS_C0013478" ON "BL_3NF"."PRODUCTS" ("ID_PRODUCT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0013404
--------------------------------------------------------

  CREATE UNIQUE INDEX "BL_3NF"."SYS_C0013404" ON "BL_3NF"."REGIONS" ("ID_REGION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0013766
--------------------------------------------------------

  CREATE UNIQUE INDEX "BL_3NF"."SYS_C0013766" ON "BL_3NF"."SALES" ("ID_SALES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0013452
--------------------------------------------------------

  CREATE UNIQUE INDEX "BL_3NF"."SYS_C0013452" ON "BL_3NF"."STORES" ("ID_STORES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0013461
--------------------------------------------------------

  CREATE UNIQUE INDEX "BL_3NF"."SYS_C0013461" ON "BL_3NF"."SUBCATEGORY" ("ID_SUBCATEGORY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ADDRESS
--------------------------------------------------------

  ALTER TABLE "BL_3NF"."ADDRESS" MODIFY ("STREET" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."ADDRESS" MODIFY ("HOUSE" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."ADDRESS" MODIFY ("CITY_ID" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."ADDRESS" ADD PRIMARY KEY ("ID_ADDRESS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CATEGORY
--------------------------------------------------------

  ALTER TABLE "BL_3NF"."CATEGORY" MODIFY ("CATEGORY_NAME" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."CATEGORY" ADD PRIMARY KEY ("ID_CATEGORY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CITIES
--------------------------------------------------------

  ALTER TABLE "BL_3NF"."CITIES" MODIFY ("CITY_NAME" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."CITIES" MODIFY ("ID_COUNTRY" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."CITIES" ADD PRIMARY KEY ("ID_CITY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONTINENTS
--------------------------------------------------------

  ALTER TABLE "BL_3NF"."CONTINENTS" MODIFY ("CONTINENT_NAME" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."CONTINENTS" ADD PRIMARY KEY ("ID_CONTINENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COUNTRIES
--------------------------------------------------------

  ALTER TABLE "BL_3NF"."COUNTRIES" MODIFY ("COUNTRY_NAME" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."COUNTRIES" MODIFY ("COUNTRY_CODE" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."COUNTRIES" MODIFY ("ID_REGION" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."COUNTRIES" ADD PRIMARY KEY ("ID_COUNTRY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CUSTOMERS
--------------------------------------------------------

  ALTER TABLE "BL_3NF"."CUSTOMERS" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."CUSTOMERS" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."CUSTOMERS" MODIFY ("ID_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."CUSTOMERS" ADD PRIMARY KEY ("ID_CUSTOMER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEES
--------------------------------------------------------

  ALTER TABLE "BL_3NF"."EMPLOYEES" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."EMPLOYEES" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."EMPLOYEES" MODIFY ("ID_JOB" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."EMPLOYEES" ADD PRIMARY KEY ("ID_EMP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table JOBS
--------------------------------------------------------

  ALTER TABLE "BL_3NF"."JOBS" MODIFY ("JOB_NAME" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."JOBS" ADD PRIMARY KEY ("ID_JOBS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PAYMENTS
--------------------------------------------------------

  ALTER TABLE "BL_3NF"."PAYMENTS" MODIFY ("PAYMENT_KEY" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."PAYMENTS" MODIFY ("ID_SALES" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."PAYMENTS" MODIFY ("ID_PRODUCT" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."PAYMENTS" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."PAYMENTS" ADD PRIMARY KEY ("ID_PAYMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "BL_3NF"."PRODUCTS" MODIFY ("PRODUCT_KEY" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."PRODUCTS" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."PRODUCTS" MODIFY ("PRODUCT_DESC" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."PRODUCTS" MODIFY ("ID_SUBCATEGORY" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."PRODUCTS" MODIFY ("PROD_COST" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."PRODUCTS" ADD PRIMARY KEY ("ID_PRODUCT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REGIONS
--------------------------------------------------------

  ALTER TABLE "BL_3NF"."REGIONS" MODIFY ("REGION_NAME" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."REGIONS" ADD PRIMARY KEY ("ID_REGION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SALES
--------------------------------------------------------

  ALTER TABLE "BL_3NF"."SALES" MODIFY ("SALES_KEY" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."SALES" MODIFY ("ID_CUSTOMER" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."SALES" MODIFY ("ID_EMPLOYEE" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."SALES" MODIFY ("ID_STORE" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."SALES" MODIFY ("DATE_SALES" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."SALES" MODIFY ("TIME_SALES" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."SALES" ADD PRIMARY KEY ("ID_SALES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STORES
--------------------------------------------------------

  ALTER TABLE "BL_3NF"."STORES" MODIFY ("STORE_KEY" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."STORES" MODIFY ("ID_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."STORES" ADD PRIMARY KEY ("ID_STORES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SUBCATEGORY
--------------------------------------------------------

  ALTER TABLE "BL_3NF"."SUBCATEGORY" MODIFY ("SUBCATEGORY_NAME" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."SUBCATEGORY" MODIFY ("ID_CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "BL_3NF"."SUBCATEGORY" ADD PRIMARY KEY ("ID_SUBCATEGORY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
