DROP TABLE CLS_CUSTOMERS;
CREATE TABLE CLS_CUSTOMERS
  (
    CUSTOMER_ID NUMBER,
    GENDER      VARCHAR2(6 BYTE),
    NAME        VARCHAR2(20 BYTE),
    SURNAME     VARCHAR2(20 BYTE),
    TITLE       VARCHAR2(4 BYTE),
    EMAIL       VARCHAR2(40 BYTE),
    PHONE       VARCHAR2(20 BYTE),
    AGE         NUMBER(2,0),
    AGE_GROUP   VARCHAR2(25 BYTE),
    BIRTHDAY    DATE,
    OCCUPATION  VARCHAR2(70 BYTE),
    COMPANY     VARCHAR2(40 BYTE),
    ADDRESS_ID  NUMBER, --city
    UPDATE_DT   DATE
  );
--COMMIT;
DROP TABLE CLS_ADDRESSES;
CREATE TABLE CLS_ADDRESSES
  (
    --address_id number primary key,
    ADDRESS     VARCHAR2(90),
    CITY_ID     NUMBER ,--references dim_cities (city_id),
    POSTAL_CODE VARCHAR2(40),
    --phone varchar2(10),
    UPDATE_DT DATE
  );
DROP TABLE CLS_CARDS;
CREATE TABLE CLS_CARDS
  (
    CCTYPE_ID NUMBER,
    BANK_ID   NUMBER,
    CVV2      VARCHAR2(250 CHAR),
    CCNUMBER  VARCHAR2(250 CHAR),
    CCEXPIRES VARCHAR2(250 CHAR)
  );
DROP TABLE CLS_CARD_TYPES;
CREATE TABLE CLS_CARD_TYPES
  (
    CARD_TYPE_ID NUMBER PRIMARY KEY,
    CCTYPE       VARCHAR2(250 CHAR)
  );
DROP TABLE CLS_SOURCES;
CREATE TABLE CLS_SOURCES
  (
    SOURCE_ID       NUMBER,
    SITE            VARCHAR2 ( 30 CHAR ),
    VISITS          NUMBER,
    TIME_ONLINE     VARCHAR2(30),
    PAGE_VIEWS      NUMBER,
    LEADING_COUNTRY VARCHAR2 ( 30 CHAR ),
    SOURCE_TAX      NUMBER,
    UPDATE_DATE     DATE
  );
DROP TABLE CLS_HOTELS;
CREATE TABLE CLS_HOTELS
  (
    HOTEL_CODE     VARCHAR2(7),
    ADDRESS_ID     NUMBER,
    CATEGORY_ID    NUMBER,
    NAME           VARCHAR2 ( 200 ),
    EMAIL          VARCHAR2 ( 200 CHAR ),
    REVIEWS_DATE   date,
    REVIEWS_RATING number
  );
DROP TABLE CLS_REGIONS;
CREATE TABLE CLS_REGIONS
  (
    REGION_CODE VARCHAR2(3),
    REGION_NAME VARCHAR2(50)
  );
DROP TABLE CLS_SUBREGIONS;
CREATE TABLE CLS_SUBREGIONS
  (
    SUBREGION_CODE VARCHAR2(4),
    SUBREGION_NAME VARCHAR2(100),
    REGION_CODE    VARCHAR(3)
  );
DROP TABLE CLS_COUNTRIES;
CREATE TABLE CLS_COUNTRIES
  (
    COUNTRY_CODE2  VARCHAR2(10),
    COUNTRY_CODE3  VARCHAR2(10),
    COUNTRY_NAME   VARCHAR2(100),
    SUBREGION_CODE VARCHAR(4)
  );
DROP TABLE CLS_CITIES;
CREATE TABLE CLS_CITIES
  (
    --city_code VARCHAR2(10),
    CITY_NAME    VARCHAR2(50),
    COUNTRY_CODE VARCHAR2(50)
  );
DROP TABLE CLS_CATEGORIES;
CREATE TABLE CLS_CATEGORIES
  (
    CATEGORY_NAME VARCHAR2(10),
    MIN_STAR       NUMBER(3),
    MAX_STAR      NUMBER(3),
    START_DT date,
    END_DT date,
    IS_ACTIVE varchar2(3),
    UPDATE_DT date
  );
DROP TABLE CLS_ORDERS;
CREATE TABLE CLS_ORDERS
  (
    CUSTOMER_ID   NUMBER,
    ORDER_DATE    DATE,
    HOTEL_ID      NUMBER,
    SOURCE_ID     NUMBER,
    CARD_ID     NUMBER,
    CHECK_IN_DATE DATE,
    DAYS_AMOUNT   NUMBER,
    AMOUNT        NUMBER,
    ROOM_TYPE     VARCHAR2(15),
    --class
    NUMBER_OF_PEOPLE NUMBER,
    DISCOUNT         NUMBER(10,2)
  );
 -- commit;
drop table cls_BANKS;
create table cls_BANKS
  ( 
    BANK_ID varchar2(8),
    BANK_NAME varchar2(250 char),
    START_DT date,
    END_DT date,
    IS_ACTIVE varchar2(3),
    DISCOUNT number,
    UPDATE_DT date
  );