CREATE TABLESPACE test_tbs
  DATAFILE 'test_data.dbf'
  SIZE 1M AUTOEXTEND ON NEXT 1M;

CREATE USER test_user IDENTIFIED BY test_user 
DEFAULT TABLESPACE test_tbs TEMPORARY TABLESPACE temp 
QUOTA UNLIMITED ON test_tbs;

GRANT CONNECT TO test_user;
GRANT RESOURCE TO test_user;
GRANT CREATE PUBLIC DATABASE LINK TO test_user;