CREATE TABLE CE_PRODUCT
  (
    PRODUCT_SRCID       NUMBER (8)    NOT NULL,
    PRODUCT_NAME        VARCHAR2 (100) NOT NULL,
    PRODUCT_PRICE       NUMBER (8)    NOT NULL,
    PRODUCT_PACKAGE     VARCHAR2 (100) NOT NULL,
    SUBCATEGORY_SRCID   NUMBER (8)    NOT NULL,
    SUPPLIER_SRCID      NUMBER (8)    NOT NULL,
    START_DT            DATE          NOT NULL,
    END_DT              DATE          NOT NULL,
    IS_ACTIVE           VARCHAR2 (20)  NOT NULL,
    CONSTRAINT "PK_PRODUCT_SRCID" PRIMARY KEY (PRODUCT_SRCID),
    CONSTRAINT "FK_SUBCATEGORY_SRCID" FOREIGN KEY (SUBCATEGORY_SRCID) REFERENCES CE_PRODUCT_SUBCATEGORY (SUBCATEGORY_SRCID),
    CONSTRAINT "FK_SUPPLIER_SRCID" FOREIGN KEY (SUPPLIER_SRCID) REFERENCES CE_SUPPLIER (SUPPLIER_SRCID)
  );