CREATE TABLE CE_SALESORDER
  (
    SALESORDER_SRCID NUMBER (8)      NOT NULL,
    OREDER_DT        DATE            NOT NULL,
    QUANTITY         NUMBER (8)      NOT NULL,
    SALES_AMOUNT     NUMBER (10)     NOT NULL,
    PAYMENT_SRCID    NUMBER (8)      NOT NULL,
    PRODUCT_SRCID    NUMBER (8)      NOT NULL,
    CUSTOMER_SRCID   NUMBER (8)      NOT NULL,
    CONSTRAINT "PK_SALESORDER_SRCID" PRIMARY KEY (SALESORDER_SRCID),
    CONSTRAINT "FK_PAYMENT_SRCID" FOREIGN KEY (PAYMENT_SRCID) REFERENCES CE_PAYMENT (PAYMENT_SRCID),
    CONSTRAINT "FK_PRODUCT_SRCID" FOREIGN KEY (PRODUCT_SRCID) REFERENCES CE_PRODUCT (PRODUCT_SRCID),
    CONSTRAINT "FK_CUSTOMER_SRCID" FOREIGN KEY (CUSTOMER_SRCID) REFERENCES CE_CUSTOMER (CUSTOMER_SRCID)
  );