DROP TABLE CLS_SOURCES;
CREATE TABLE CLS_SOURCES
  (
    SOURCE_3NF_ID   NUMBER NOT NULL,
    SOURCE_ID       NUMBER,
    SITE            VARCHAR2 ( 30 CHAR ) NOT NULL,
    VISITS          NUMBER,
    TIME_ONLINE     VARCHAR2(30),
    PAGE_VIEWS      NUMBER,
    LEADING_COUNTRY VARCHAR2 ( 30 CHAR ),
    SOURCE_TAX      NUMBER NOT NULL,
    UPDATE_DATE     DATE
  );
DROP TABLE CLS_CARDS;
CREATE TABLE CLS_CARDS
  (
    CARD_3NF_ID NUMBER PRIMARY KEY,
    BANK_NAME   VARCHAR2(250 CHAR) NOT NULL,
    START_DT    DATE,
    END_DT      DATE,
    IS_ACTIVE   VARCHAR2(3) ,
    DISCOUNT    NUMBER,
    CCTYPE      VARCHAR2(250 CHAR) NOT NULL,
    CVV2        VARCHAR2(250 CHAR),
    CCNUMBER    VARCHAR2(250 CHAR) NOT NULL,
    CCEXPIRES   VARCHAR2(250 CHAR)
  );
DROP TABLE CLS_HOTELS;
CREATE TABLE CLS_HOTELS
  (
    HOTEL_3NF_ID   NUMBER ,
    HOTEL_CODE     VARCHAR2(10),
    HOTEL_NAME     VARCHAR2(200),
    CATEGORY_NAME  VARCHAR2(30),-- references dim_categories(category_id),
    START_DT       DATE,
    END_DT         DATE,
    IS_ACTIVE      VARCHAR2(3) ,
    ADDRESS_ID     NUMBER,-- references dim_addresses(address_id),
    EMAIL          VARCHAR2 ( 200 CHAR ),
    UPDATE_DT      DATE,
    REVIEWS_DATE   DATE,
    REVIEWS_RATING NUMBER
  );
DROP TABLE CLS_CUSTOMERS;
CREATE TABLE CLS_CUSTOMERS
  (
    CUSTOMER_3NF_ID  NUMBER NOT NULL,
    CUSTOMER_ID      NUMBER,
    GENDER           VARCHAR2(6),
    NAME             VARCHAR2(20),
    SURNAME          VARCHAR2(20),
    TITLE            VARCHAR2(4),
    EMAIL            VARCHAR2(40),
    TELEPHONE_NUMBER VARCHAR2(20),
    AGE              NUMBER (2),
    AGE_GROUP        VARCHAR2(20),
    BIRTHDAY         DATE,
    OCCUPATION       VARCHAR2(70),
    COMPANY          VARCHAR2(40),
    ADDRESS          VARCHAR2(90),-- number references dim_addresses(address_id),
    CITY_NAME        VARCHAR2(50),
    COUNTRY_NAME     VARCHAR2(100) NOT NULL,
    SUBREGION_NAME   VARCHAR2(100) NOT NULL,
    REGION_NAME      VARCHAR2(50) NOT NULL,
    UPDATE_DT        DATE
  );
DROP TABLE CLS_DATE;
CREATE TABLE CLS_DATE
  (
    DATE_ID             DATE NOT NULL,
    DATE_LINE           VARCHAR2(20),
    DATE_FORMAT         VARCHAR2(20),
    WEEK_DAY_FULL       VARCHAR2(20),
    WEEK_DAY_SHORT      VARCHAR2(20),
    DAY_NUM_OF_WEEK     NUMBER,
    DAY_NUM_OF_MONTH    NUMBER,
    DAY_NUM_OF_YEAR     NUMBER,
    MONTH_ID            VARCHAR2(10),
    MONTH_SHORT         VARCHAR2(20),
    MONTH_LONG          VARCHAR2(20),
    MONTH_NUM_OF_YEAR   NUMBER,
    QUARTER_ID          VARCHAR2(20),
    QUARTER             VARCHAR2(20),
    QUARTER_NUM_OF_YEAR NUMBER,
    YEAR_ID             VARCHAR2(20)
  );
DROP TABLE CLS_ORDERS;
CREATE TABLE CLS_ORDERS
  (
    CUSTOMER_ID   NUMBER NOT NULL,
    ORDER_DATE    DATE NOT NULL,
    HOTEL_ID      NUMBER NOT NULL,
    SOURCE_ID     NUMBER NOT NULL,
    card_id number not null,
    CHECK_IN_DATE DATE NOT NULL,
    DAYS_AMOUNT   NUMBER,
    AMOUNT        NUMBER,
    ROOM_TYPE     VARCHAR2(15),
    --class
    NUMBER_OF_PEOPLE NUMBER,
    DISCOUNT         NUMBER(10,2)
  );
