DROP TABLE "CE_Brands" CASCADE CONSTRAINTS
;

DROP TABLE "CE_Categories" CASCADE CONSTRAINTS
;

DROP TABLE "CE_Colors" CASCADE CONSTRAINTS
;

DROP TABLE "CE_Customers" CASCADE CONSTRAINTS
;

DROP TABLE "CE_Deliveries" CASCADE CONSTRAINTS
;

DROP TABLE "CE_Districts" CASCADE CONSTRAINTS
;

DROP TABLE "CE_Location_types" CASCADE CONSTRAINTS
;

DROP TABLE "CE_Locations" CASCADE CONSTRAINTS
;

DROP TABLE "CE_OrderItems" CASCADE CONSTRAINTS
;

DROP TABLE "CE_Orders" CASCADE CONSTRAINTS
;

DROP TABLE "CE_PayOptions" CASCADE CONSTRAINTS
;

DROP TABLE "CE_Points" CASCADE CONSTRAINTS
;

DROP TABLE "CE_Products" CASCADE CONSTRAINTS
;

DROP TABLE "CE_Regions" CASCADE CONSTRAINTS
;

DROP TABLE "CE_Subcategories" CASCADE CONSTRAINTS
;

DROP TABLE "CE_Types" CASCADE CONSTRAINTS
;

CREATE TABLE "CE_Brands"
(
	"BRAND_SURR_ID" NUMBER(3) NOT NULL,
	"BRAND_CODE" VARCHAR2(3),
	"BRAND_DESC" VARCHAR2(100),
	"INSERT_ID" DATE
)
;

CREATE TABLE "CE_Categories"
(
	"CATEGORY_SURR_ID" NUMBER(2) NOT NULL,
	"CATEGOTY_DESC" VARCHAR2(50),
	"INSERT_DT" DATE
)
;

CREATE TABLE "CE_Colors"
(
	"COLOR_SURR_ID" NUMBER(2) NOT NULL,
	"COLOR_DESC" VARCHAR2(25),
	"INSERT_DT" DATE
)
;

CREATE TABLE "CE_Customers"
(
	"CUSTOMER_SURR_ID" NUMBER(8) NOT NULL,
	"CUSTOMER_CODE" NUMBER(7),
	"LAST_NAME" VARCHAR2(50),
	"FIRST_NAME" VARCHAR2(50),
	"MIDDLE_NAME" VARCHAR2(50),
	"BIRTHDATE" DATE,
	"GENDER" VARCHAR2(1),
	"PERSONAL_DISCOUNT" NUMBER(2),
	"ADDRESS" VARCHAR2(100),
	"LOCATION_SURR_ID" NUMBER(5),
	"START_DT" DATE,
	"END_DT" DATE,
	"IS_ACTIVE" VARCHAR2(1),
	"INSERT_DT" DATE
)
;

CREATE TABLE "CE_Deliveries"
(
	"DELIVERY_SURR_ID" NUMBER(2) NOT NULL,
	"DELIVERY_DESC" VARCHAR2(50),
	"INSERT_DT" DATE
)
;

CREATE TABLE "CE_Districts"
(
	"DISTRICT_SURR_ID" NUMBER(3) NOT NULL,
	"DISTRICT_DESC" VARCHAR2(50),
	"REGION_SURR_ID" NUMBER(1),
	"INSERT_DT" DATE
)
;

CREATE TABLE "CE_Location_types"
(
	"LOCATION_SURR_TYPE_ID" NUMBER(2) NOT NULL,
	"TYPE_DESC_SHORT" VARCHAR2(5),
	"TYPE_DESC_FULL" VARCHAR2(50),
	"INSERT_DT" DATE
)
;

CREATE TABLE "CE_Locations"
(
	"LOCATION_SURR_ID" NUMBER(5) NOT NULL,
	"LOCATION_CODE" VARCHAR2(5),
	"LOCATION_DESC" VARCHAR2(50),
	"LOCATION_SURR_TYPE_ID" NUMBER(2),
	"DISTRICT_ID" NUMBER(3),
	"INSERT_DT" DATE
)
;

CREATE TABLE "CE_OrderItems"
(
	"ITEM_SURR_ID" NUMBER(8) NOT NULL,
	"ORDER_SURR_ID" NUMBER(10),
	"ITEM_NUM" NUMBER(3),
	"PRODUCT_SURR_ID" NUMBER(8),
	"PRICE" NUMBER(6),
	"QUANTITY" NUMBER(3),
	"DISCOUNT" NUMBER(2),
	"ITEM_SUM" NUMBER(10,2),
	"DISCOUNT_SUM" NUMBER(10,2),
	"TOTAL_SUM" NUMBER(10,2),
	"INSERT_DT" DATE
)
;

CREATE TABLE "CE_Orders"
(
	"ORDER_SURR_ID" NUMBER(10) NOT NULL,
	"ORDER_CODE" NUMBER(10),
	"ORDER_DATE" DATE,
	"PAYMENT_DATE" DATE,
	"CUSTOMER_SURR_ID" NUMBER(8),
	"DELIVERY_SURR_ID" NUMBER(2),
	"PAYOPTION_SURR_ID" NUMBER(2),
	"POINT_SURR_ID" NUMBER(3),
	"ORDER_SUM" NUMBER(15),
	"DISCOUNT_SUM" NUMBER(15),
	"TOTAL_SUM" NUMBER(15),
	"INSERT_DT" DATE
)
;

CREATE TABLE "CE_PayOptions"
(
	"PAYOPTION_SURR_ID" NUMBER(2) NOT NULL,
	"PAYOPTION_DESC" VARCHAR2(50),
	"INSERT_DT" DATE
)
;

CREATE TABLE "CE_Points"
(
	"POINT_SURR_ID" NUMBER(3) NOT NULL,
	"POINT_CODE" VARCHAR2(3),
	"POINT_ADDRESS" VARCHAR2(50),
	"LOCATION_SURR_ID" NUMBER(5),
	"INSERT_DT" DATE
)
;

CREATE TABLE "CE_Products"
(
	"PRODUCT_SURR_ID" NUMBER(8) NOT NULL,
	"PRODUCT_CODE" NUMBER(9),
	"PRODUCT_DESC" VARCHAR2(50),
	"PRODUCT_VENDORCODE" NUMBER(8),
	"COLOR_SURR_ID" NUMBER(2),
	"TYPE_SURR_ID" NUMBER(4),
	"BRAND_SURR_ID" NUMBER(3),
	"START_DT" DATE,
	"END_DT" DATE,
	"IS_ACTIVE" VARCHAR2(1),
	"INSERT_DT" DATE
)
;

CREATE TABLE "CE_Regions"
(
	"REGION_SURR_ID" NUMBER(1) NOT NULL,
	"REGION_DESC" VARCHAR2(50),
	"INSERT_DT" DATE
)
;

CREATE TABLE "CE_Subcategories"
(
	"SUBCATEGORY_SURR_ID" NUMBER(3) NOT NULL,
	"SUBCATEGORY_DESC" VARCHAR2(150),
	"CATEGORY_SURR_ID" NUMBER(2),
	"INSERT_ID" VARCHAR2(50)
)
;

CREATE TABLE "CE_Types"
(
	"TYPE_SURR_ID" NUMBER(4) NOT NULL,
	"TYPE_CODE" NUMBER(8),
	"TYPE_DESC" VARCHAR2(100),
	"SUBCATEGORY_SURR_ID" NUMBER(3),
	"INSERT_DT" DATE
)
;

ALTER TABLE "CE_Brands" 
 ADD CONSTRAINT "PK_BRAND"
	PRIMARY KEY ("BRAND_SURR_ID") USING INDEX
;

ALTER TABLE "CE_Categories" 
 ADD CONSTRAINT "PK_CATEGORY"
	PRIMARY KEY ("CATEGORY_SURR_ID") USING INDEX
;

ALTER TABLE "CE_Colors" 
 ADD CONSTRAINT "PK_CE_Colors"
	PRIMARY KEY ("COLOR_SURR_ID") USING INDEX
;

ALTER TABLE "CE_Customers" 
 ADD CONSTRAINT "PK_CUSTOMER"
	PRIMARY KEY ("CUSTOMER_SURR_ID") USING INDEX
;

ALTER TABLE "CE_Deliveries" 
 ADD CONSTRAINT "PK_DELIVERY"
	PRIMARY KEY ("DELIVERY_SURR_ID") USING INDEX
;

ALTER TABLE "CE_Districts" 
 ADD CONSTRAINT "PK_DISTRICT"
	PRIMARY KEY ("DISTRICT_SURR_ID") USING INDEX
;

ALTER TABLE "CE_Location_types" 
 ADD CONSTRAINT "PK_LOCATION_TYP_01"
	PRIMARY KEY ("LOCATION_SURR_TYPE_ID") USING INDEX
;

ALTER TABLE "CE_Locations" 
 ADD CONSTRAINT "PK_LOCATION"
	PRIMARY KEY ("LOCATION_SURR_ID") USING INDEX
;

ALTER TABLE "CE_OrderItems" 
 ADD CONSTRAINT "PK_OrderItem"
	PRIMARY KEY ("ITEM_SURR_ID") USING INDEX
;

ALTER TABLE "CE_Orders" 
 ADD CONSTRAINT "PK_ORDER"
	PRIMARY KEY ("ORDER_SURR_ID") USING INDEX
;

ALTER TABLE "CE_PayOptions" 
 ADD CONSTRAINT "PK_PAYOPTION"
	PRIMARY KEY ("PAYOPTION_SURR_ID") USING INDEX
;

ALTER TABLE "CE_Points" 
 ADD CONSTRAINT "PK_PICKUPPOINT"
	PRIMARY KEY ("POINT_SURR_ID") USING INDEX
;

ALTER TABLE "CE_Products" 
 ADD CONSTRAINT "PK_PRODUCT"
	PRIMARY KEY ("PRODUCT_SURR_ID") USING INDEX
;

ALTER TABLE "CE_Regions" 
 ADD CONSTRAINT "PK_REGION"
	PRIMARY KEY ("REGION_SURR_ID") USING INDEX
;

ALTER TABLE "CE_Subcategories" 
 ADD CONSTRAINT "PK_SUBCATEGORY"
	PRIMARY KEY ("SUBCATEGORY_SURR_ID") USING INDEX
;

ALTER TABLE "CE_Types" 
 ADD CONSTRAINT "PK_PRODUCT_TYPE"
	PRIMARY KEY ("TYPE_SURR_ID") USING INDEX
;

ALTER TABLE "CE_Customers" 
 ADD CONSTRAINT "FK_CUSTOMER_LOCATION"
	FOREIGN KEY ("LOCATION_SURR_ID") REFERENCES "CE_Locations" ("LOCATION_SURR_ID")
;

ALTER TABLE "CE_Districts" 
 ADD CONSTRAINT "FK_DISTRICT_REGION"
	FOREIGN KEY ("REGION_SURR_ID") REFERENCES "CE_Regions" ("REGION_SURR_ID")
;

ALTER TABLE "CE_Locations" 
 ADD CONSTRAINT "FK_LOCATION_AREA"
	FOREIGN KEY ("DISTRICT_ID") REFERENCES "CE_Districts" ("DISTRICT_SURR_ID")
;

ALTER TABLE "CE_Locations" 
 ADD CONSTRAINT "FK_LOCATION_LOCATION_TYPE"
	FOREIGN KEY ("LOCATION_SURR_TYPE_ID") REFERENCES "CE_Location_types" ("LOCATION_SURR_TYPE_ID")
;

ALTER TABLE "CE_OrderItems" 
 ADD CONSTRAINT "FK_OrderItem_Order"
	FOREIGN KEY ("ORDER_SURR_ID") REFERENCES "CE_Orders" ("ORDER_SURR_ID")
;

ALTER TABLE "CE_OrderItems" 
 ADD CONSTRAINT "FK_OrderItem_Product"
	FOREIGN KEY ("PRODUCT_SURR_ID") REFERENCES "CE_Products" ("PRODUCT_SURR_ID")
;

ALTER TABLE "CE_Orders" 
 ADD CONSTRAINT "FK_ORDER_CUSTOMER"
	FOREIGN KEY ("CUSTOMER_SURR_ID") REFERENCES "CE_Customers" ("CUSTOMER_SURR_ID")
;

ALTER TABLE "CE_Orders" 
 ADD CONSTRAINT "FK_ORDER_DELIVERY"
	FOREIGN KEY ("DELIVERY_SURR_ID") REFERENCES "CE_Deliveries" ("DELIVERY_SURR_ID")
;

ALTER TABLE "CE_Orders" 
 ADD CONSTRAINT "FK_ORDER_PAYOPTION"
	FOREIGN KEY ("PAYOPTION_SURR_ID") REFERENCES "CE_PayOptions" ("PAYOPTION_SURR_ID")
;

ALTER TABLE "CE_Orders" 
 ADD CONSTRAINT "FK_ORDER_PICKUPPOINT"
	FOREIGN KEY ("POINT_SURR_ID") REFERENCES "CE_Points" ("POINT_SURR_ID")
;

ALTER TABLE "CE_Points" 
 ADD CONSTRAINT "FK_PICKUPPOINT_LOCATION"
	FOREIGN KEY ("LOCATION_SURR_ID") REFERENCES "CE_Locations" ("LOCATION_SURR_ID")
;

ALTER TABLE "CE_Products" 
 ADD CONSTRAINT "FK_CE_Products_CE_Brands"
	FOREIGN KEY ("BRAND_SURR_ID") REFERENCES "CE_Brands" ("BRAND_SURR_ID")
;

ALTER TABLE "CE_Products" 
 ADD CONSTRAINT "FK_CE_Products_CE_Colors"
	FOREIGN KEY ("COLOR_SURR_ID") REFERENCES "CE_Colors" ("COLOR_SURR_ID")
;

ALTER TABLE "CE_Products" 
 ADD CONSTRAINT "FK_Product_Type"
	FOREIGN KEY ("TYPE_SURR_ID") REFERENCES "CE_Types" ("TYPE_SURR_ID")
;

ALTER TABLE "CE_Subcategories" 
 ADD CONSTRAINT "FK_SUBCAT_CAT"
	FOREIGN KEY ("CATEGORY_SURR_ID") REFERENCES "CE_Categories" ("CATEGORY_SURR_ID")
;

ALTER TABLE "CE_Types" 
 ADD CONSTRAINT "FK_TYPE_SUBCAT"
	FOREIGN KEY ("SUBCATEGORY_SURR_ID") REFERENCES "CE_Subcategories" ("SUBCATEGORY_SURR_ID")
;
