ALTER TABLE FCT_SALES_DD
 ADD CONSTRAINT "PK_FCT_SALES_DD"
	PRIMARY KEY ("PRODUCT_ID") USING INDEX
;

ALTER TABLE DIM_STORES
 ADD CONSTRAINT "PK_DIM_STORES"
	PRIMARY KEY ("STORE_SURR_ID") USING INDEX
;

ALTER TABLE DIM_PROVIDERS 
 ADD CONSTRAINT "PK_DIMPROVIDER"
	PRIMARY KEY ("PROVIDER_SURR_ID") USING INDEX
;

ALTER TABLE DIM_PRODUCTS_SCD 
 ADD CONSTRAINT "PK_DIMPRODUCT"
	PRIMARY KEY ("PRODUCT_ID") USING INDEX
;

ALTER TABLE DIM_EMPLOYEES
 ADD CONSTRAINT "PK_DIM_EMPLOYEES"
	PRIMARY KEY ("EMPLOYEE_SURR_ID") USING INDEX
;

ALTER TABLE DIM_DATES
 ADD CONSTRAINT "PK_DIMDATE"
	PRIMARY KEY ("DATE_ID") USING INDEX
;

ALTER TABLE DIM_CUSTOMERS_SCD
 ADD CONSTRAINT "PK_DIM_CUSTOMERS"
	PRIMARY KEY ("CUSTOMER_SURR_ID") USING INDEX
;

ALTER TABLE DIM_COUNTRIES
 ADD CONSTRAINT "PK_DIM_COUNTRIES"
	PRIMARY KEY ("COUNTRY_SURR_ID") USING INDEX
;

ALTER TABLE DIM_CITIES
 ADD CONSTRAINT "PK_DIM_ADDRESSES"
	PRIMARY KEY ("CITY_SURR_ID") USING INDEX
;

ALTER TABLE FCT_SALES_DD
 ADD CONSTRAINT "FK_FACT_SALES_DIM_CUSTOMERS"
	FOREIGN KEY ("CUSTOMER_ID") REFERENCES "ora_owner"."DIM_CUSTOMERS_SCD" ("CUSTOMER_SURR_ID")
;

ALTER TABLE FCT_SALES_DD
 ADD CONSTRAINT "FK_FACT_SALES_DIM_DATES"
	FOREIGN KEY ("DATE_ID") REFERENCES "ora_owner"."DIM_DATES" ("DATE_ID")
;

ALTER TABLE FCT_SALES_DD
 ADD CONSTRAINT "FK_FACT_SALES_DIM_EMPLOYEES"
	FOREIGN KEY ("EMPLOYEE_ID") REFERENCES "ora_owner"."DIM_EMPLOYEES" ("EMPLOYEE_SURR_ID")
;

ALTER TABLE FCT_SALES_DD
 ADD CONSTRAINT "FK_FACT_SALES_DIM_PRODUCTS02"
	FOREIGN KEY ("PRODUCT_ID") REFERENCES "ora_owner"."DIM_PRODUCTS_SCD" ("PRODUCT_ID")
;

ALTER TABLE FCT_SALES_DD
 ADD CONSTRAINT "FK_FACT_SALES_DIM_STORES"
	FOREIGN KEY ("STORE_ID") REFERENCES "ora_owner"."DIM_STORES" ("STORE_SURR_ID")
;

ALTER TABLE DIM_STORES
 ADD CONSTRAINT "FK_DIM_STORES_DIM_ADDRESSES02"
	FOREIGN KEY ("ADDRESS") REFERENCES "ora_owner"."DIM_CITIES" ("CITY_SURR_ID")
;

ALTER TABLE DIM_PROVIDERS
 ADD CONSTRAINT "FK_DIM_PROVIDERS_DIM_ADDRESSES"
	FOREIGN KEY ("ADDRESS") REFERENCES "ora_owner"."DIM_CITIES" ("CITY_SURR_ID")
;

ALTER TABLE DIM_PRODUCTS_SCD
 ADD CONSTRAINT "FK_DIM_PRODUCTS_DIM_PROVIDERS"
	FOREIGN KEY ("PROVIDER_ID") REFERENCES "ora_owner"."DIM_PROVIDERS" ("PROVIDER_SURR_ID")
;

ALTER TABLE DIM_EMPLOYEES
 ADD CONSTRAINT "FK_DIM_EMPLOYEES_DIM_CITIES"
	FOREIGN KEY ("CITY_ID") REFERENCES "ora_owner"."DIM_CITIES" ("CITY_SURR_ID")
;

ALTER TABLE DIM_CUSTOMERS_SCD
 ADD CONSTRAINT "FK_DIM_CUSTOMERS_DIM_ADDRESS02"
	FOREIGN KEY ("CITY_ID") REFERENCES "ora_owner"."DIM_CITIES" ("CITY_SURR_ID")
;

ALTER TABLE DIM_CITIES 
 ADD CONSTRAINT "FK_DIM_ADDRESSES_DIM_COUNTRIES"
	FOREIGN KEY ("COUNTRY_ID") REFERENCES "ora_owner"."DIM_COUNTRIES" ("COUNTRY_SURR_ID")
;
