CREATE TABLE DIM_EMPLOYEES
(
	"EMPLOYEE_SURR_ID" NUMBER(8) NOT NULL,
	"EMPLOYEE_CODE" VARCHAR2(50) NOT NULL,
	"LAST_NAME" VARCHAR2(50) NOT NULL,
	"FIRST_NAME" VARCHAR2(50) NOT NULL,
	"ADDRESS" VARCHAR2(200) NOT NULL,
	"CITY_ID" NUMBER(8,2) NOT NULL,
	"EMAIL" VARCHAR2(50) NOT NULL,
	"PHONE" VARCHAR2(50) NOT NULL,
	"MANAGER_ID" NUMBER(4) NOT NULL,
	"INSERT_DT" DATE NOT NULL,
	"UPDATE_DT" DATE NOT NULL
)
;