CREATE TABLE DIM_CITIES
(
	"CITY_SURR_ID" NUMBER(8) NOT NULL,
	"CITY_CODE" VARCHAR2(50) NOT NULL,
	"CITY" VARCHAR2(50) NOT NULL,
	"POSTAL_CODE" VARCHAR2(50) NOT NULL,
	"COUNTRY_ID" NUMBER(8) NOT NULL
)
;