CREATE TABLE DIM_PRODUCTS_SCD
(
	"PRODUCT_ID" NUMBER(8) NOT NULL,
	"PRODUCT_CODE" NUMBER(8) NOT NULL,
	"PRODUCT_NAME" VARCHAR2(150) NOT NULL,
	"CATEGORY_NAME" VARCHAR2(50) NOT NULL,
	"SUBCATEGORY_NAME" VARCHAR2(50) NOT NULL,
	"PROVIDER_ID" NUMBER(8) NOT NULL,
	"MANUFACTURER_COUNTRY" VARCHAR2(50) NOT NULL,
	"START_DT" DATE NOT NULL,
	"END_DT" DATE NOT NULL,
	"IS_ACTIVE" VARCHAR2(5) NOT NULL,
	"INSERT_DT" DATE NOT NULL
)
;