CREATE TABLE DIM_STORES
(
	"STORE_SURR_ID" NUMBER(8) NOT NULL,
	"STORE_CODE" NUMBER(4) NOT NULL,
	"ADDRESS" VARCHAR2(200) NOT NULL,
	"CITY_ID" NUMBER(8) NOT NULL,
	"EMAIL" VARCHAR2(50) NOT NULL,
	"PHONE" VARCHAR2(50) NOT NULL,
	"INSERT_DT" DATE NOT NULL,
	"UPDATE_DT" DATE NOT NULL
)
;