CREATE TABLE DIM_CUSTOMERS_SCD
(
	"CUSTOMER_SURR_ID" NUMBER(9) NOT NULL,
	"CUSTOMER_CODE" NUMBER(8) NOT NULL,
	"LAST_NAME" VARCHAR2(50) NOT NULL,
	"FIRST_NAME" VARCHAR2(50) NOT NULL,
	"ADDRESS" VARCHAR2(50) NOT NULL,
	"CITY_ID" NUMBER(8) NOT NULL,
	"EMAIL" VARCHAR2(50) NOT NULL,
	"PHONE" VARCHAR2(50) NOT NULL,
	"AGE" NUMBER(3) NOT NULL,
	"AGE_GROUP" VARCHAR2(50) NOT NULL,
	"START_DT" DATE NOT NULL,
	"END_DT" DATE NOT NULL,
	"IS_ACTIVE" VARCHAR2(5) NOT NULL,
	"INSERT_DT" DATE NOT NULL
)
;