CREATE TABLE FCT_SALES_DD
(
	"PRODUCT_ID" NUMBER(8) NOT NULL,
	"DATE_ID" DATE NOT NULL,
	"CUSTOMER_ID" NUMBER(8) NOT NULL,
	"STORE_ID" NUMBER(8) NOT NULL,
	"EMPLOYEE_ID" NUMBER(8) NOT NULL,
	"AMOUNT_OF_SOLD_ITEMS" NUMBER(8,2) NOT NULL,
	"UNIT COST" NUMBER(5,2) NOT NULL,
	"TOTAL COST" NUMBER(5,2) NOT NULL,
	"SALE_ID" NUMBER(8) NOT NULL
)
;