CREATE VIEW DIM_LOCATIONS AS
  SELECT TO_NUMBER (NULL) AS CHILD_ID,
    'WORLD'               AS LEVEL_NAME,
    WORLD_ID              AS PARENT_ID,
    WORLD_DESC            AS NAME
  FROM CE_WORLDS
UNION ALL
  SELECT W.WORLD_ID AS CHILD_ID,
    'CONTINENT'     AS LEVEL_NAME,
    C.CONTINENT_ID  AS PARENT_ID,
    CONTINENT_DESC  AS NAME
  FROM CE_CONTINENTS C JOIN CE_WORLDS W ON C.WORLD_ID=W.WORLD_ID
UNION ALL
  SELECT C.CONTINENT_ID AS CHILD_ID,
    'REGION'            AS LEVEL_NAME,
    R.REGION_ID         AS PARENT_ID,
    R.REGION_DESC       AS NAME
  FROM CE_REGIONS R JOIN CE_CONTINENTS C ON R.CONTINENT_ID=C.CONTINENT_ID
UNION ALL
  SELECT R.REGION_ID AS CHILD_ID,
    'COUNTRY'        AS LEVEL_NAME,
    C.COUNTRY_ID     AS PARENT_ID,
    C.COUNTRY_DESC   AS NAME
  FROM CE_COUNTRIES C JOIN CE_REGIONS R ON C.REGION_ID=R.REGION_ID;
