@USER_[bl_cl].sql

CONNECT bl_cl/123456;
show user;

@DROP_proc(updated).sql;
@bl_cl_[DDL-DROP].sql;
@bl_cl_[DDL-WRK-SYNONYMS].sql;
@CLS_SALES.sql;
@CLS_PROMOTIONS.sql;
@CLS_CONSUMERS.sql;
@CLS_DEPARTMENTS.sql;
@CLS_ADDRESSES.sql;
@CLS_CITIES.sql;
@CLS_COUNTRIES.sql;
@CLS_SUBREGIONS.sql;
@CLS_REGIONS.sql;
@CLS_CONSUMER_RATE.sql;
@CLS_RESPONSIBLE.sql;
@CLS_OCCUPATION.sql;
@CLS_LOCALIZATION.sql;
@CLS_PRODUCTS.sql;
@CLS_PRODUCT_SUBCATEGORY.sql;
@CLS_PRODUCT_CATEGORY.sql;

@pkg_CE_DML.sql

execute CE_DDL.CE_REGIONS;
execute CE_DDL.CE_SUBREGIONS;
execute CE_DDL.CE_LOCALIZATION;
execute CE_DDL.CE_COUNTRIES;
execute CE_DDL.CE_CITIES;
execute CE_DDL.CE_ADDRESSES;
execute CE_DDL.CE_PRODUCTS;
execute CE_DDL.CE_PRODUCT_CATEGORY;
execute CE_DDL.CE_PRODUCT_SUBCATEGORY;
execute CE_DDL.CE_CONSUMER_RATE;
execute CE_DDL.CE_OCCUPATION;
execute CE_DDL.CE_RESPONSIBLE;
execute CE_DDL.CE_CONSUMERS;
execute CE_DDL.CE_DEPARTMENTS;
execute CE_DDL.CE_PROMOTIONS;
execute CE_DDL.CE_SALES;