-- CLS_PRODUCT_SUBCATEGORY
execute pkg_drop.DROP_proc('CLS_PRODUCT_SUBCATEGORY','table');           
CREATE TABLE CLS_PRODUCT_SUBCATEGORY
(
	"SUBCATEGORY_CODE" VARCHAR2(50),
	"SUBCATEGORY_NAME" VARCHAR2(50),
	"CATEGORY_CODE" VARCHAR(10),
	"SIZE" NUMBER(3) DEFAULT ON NULL '-98',
	"TOBACCO" NUMBER(3,1) DEFAULT ON NULL '-99',
	"UPDATE_DT" DATE,
	"INSERT_DT" DATE DEFAULT TRUNC(SYSDATE)
)
;
