-- CLS_SALES
execute pkg_drop.DROP_proc('cls_SALES','table');
CREATE TABLE cls_SALES
(
	"SALE_DATE" DATE,
	"DEPARTMENT_CODE" VARCHAR2(20),
	"CONSUMER_CODE" VARCHAR2(20),
	"PRODUCT_CODE" VARCHAR2(20),
	"PROMO_CODE" VARCHAR2(20),
  "AMOUNT" NUMBER(10),
	"UPDATE_DT" DATE,
	"INSERT_DT" DATE DEFAULT TRUNC(SYSDATE)
)
;