-- CLS_SUBREGIONS
execute pkg_drop.DROP_proc('CLS_SUBREGIONS','table');
CREATE TABLE CLS_SUBREGIONS (
  SUBREGION_CODE VARCHAR2(4),
  SUBREGION_NAME VARCHAR2(100),
  REGION_CODE VARCHAR(3),
  "UPDATE_DT" DATE,
	"INSERT_DT" DATE DEFAULT TRUNC(SYSDATE)
  );