-- CLS_DEPARTMENTS
execute pkg_drop.DROP_proc('cls_DEPARTMENTS','table');
CREATE TABLE cls_DEPARTMENTS
(
	"DEPARTMENT_CODE" VARCHAR2(10),
	"DEPARTMENT_DESC" VARCHAR2(50),
	"ADDRESS_CODE" VARCHAR2(10),
  "START_DT" DATE,
  "END_DT" DATE,
  "IS_ACTIVE" VARCHAR(1),
	"UPDATE_DT" DATE,
	"INSERT_DT" DATE DEFAULT TRUNC(SYSDATE)
)
;