-- CLS_PRODUCTS
execute pkg_drop.DROP_proc('CLS_PRODUCTS','table');           
CREATE TABLE CLS_PRODUCTS
(
	"PRODUCT_CODE" VARCHAR2(20),
	"PRODUCT_NAME" VARCHAR2(50),
	"LOCALIZATION_CODE" VARCHAR(10),
	"CATEGORY_CODE" VARCHAR2(20),
  "PRICE" NUMBER (8,2),
	"UPDATE_DT" DATE,
	"INSERT_DT" DATE DEFAULT TRUNC(SYSDATE)
)
;