-- CLS_PROMOTIONS
execute pkg_drop.DROP_proc('cls_PROMOTIONS','table');
CREATE TABLE cls_PROMOTIONS (
  PROMO_CODE VARCHAR2(10),
  PROMO_NAME VARCHAR2(50),
  PROMO_DESC VARCHAR2(255),
  PROMO_COST NUMBER(8,2),
  START_DT DATE,
  END_DT DATE,
  IS_ACTIVE VARCHAR2(1) DEFAULT 'Y'
)
;