-- CLS_REGIONS
execute pkg_drop.DROP_proc('CLS_REGIONS','table');
CREATE TABLE CLS_REGIONS (
  REGION_CODE VARCHAR2(3),
  REGION_NAME VARCHAR2(50),
  "UPDATE_DT" DATE,
	"INSERT_DT" DATE DEFAULT TRUNC(SYSDATE)
  );