-- CLS_CONSUMERS
execute pkg_drop.DROP_proc('CLS_CONSUMERS','table');
CREATE TABLE CLS_CONSUMERS
(
	"CONSUMER_CODE" VARCHAR(20),
	"CONSUMER_TITLE" VARCHAR2(100),
	"CONSUMER_RATE_CODE" VARCHAR(10),
	"ADDRESS_CODE" VARCHAR(50),
	"RESP_CODE" VARCHAR2(10),
	"UPDATE_DT" DATE,
	"INSERT_DT" DATE DEFAULT TRUNC(SYSDATE)
)
;