CREATE OR REPLACE PACKAGE BODY PKG_ETL_INSERT_ATE
AS
  PROCEDURE INSERT_TABLE_ATE
    IS
    BEGIN 
    EXECUTE IMMEDIATE ('TRUNCATE TABLE CLS_ATE');
    INSERT INTO CLS_ATE(ATE_NAME,COUNTRY_code) 
    SELECT * FROM (SELECT distinct(nvl(STATEFULL,'-99')),country
    FROM WRK_CUSTOMERS CUST
UNION 
SELECT distinct(nvl(STATEFULL,'-99')),country
    FROM WRK_SUPPLIERS); 
    COMMIT;
    EXCEPTION WHEN OTHERS THEN RAISE;
  END INSERT_TABLE_ATE;
---  
  PROCEDURE MERGE_TABLE_ATE
  IS 
  BEGIN 
  MERGE INTO bl_3nf.ce_ATE NFATE USING
    (SELECT 
     ATE_SRCID,
      ATE_NAME,
      C.COUNTRY_SRCID
        FROM CLS_ATE, BL_3NF.CE_COUNTRY C
        WHERE CLS_ATE.COUNTRY_CODE = C.COUNTRY_CODE 
    MINUS
     SELECT 
      ATE_SRCID,
      ATE_NAME,
      COUNTRY_SRCID
    FROM bl_3nf.ce_ATE
    ) CLSA ON (CLSA.ATE_SRCID =NFATE.ATE_SRCID)
  WHEN MATCHED THEN 
    UPDATE SET NFATE.ATE_NAME = CLSA.ATE_NAME
  WHEN NOT MATCHED THEN
    INSERT 
      (
        ATE_SRCID,
        ATE_NAME,
        COUNTRY_SRCID 
      )
    VALUES
      (
        bl_3nf.ATE_SEQ.NEXTVAL,
        CLSA.ATE_NAME,
        CLSA.COUNTRY_SRCID
      );
    COMMIT;
  EXCEPTION 
    WHEN OTHERS THEN RAISE ;
  END MERGE_TABLE_ATE;
END PKG_ETL_INSERT_ATE;
/