-- Create a new tablespace. 

CREATE TABLESPACE tbs_dwh DATAFILE
    'TBS_DWH.DBF' SIZE 104857600
        AUTOEXTEND ON NEXT 20971520
NOLOGGING SEGMENT SPACE MANAGEMENT AUTO EXTENT MANAGEMENT LOCAL AUTOALLOCATE;