exec  FRAMEWORK.pkg_utl_drop.proc_drop_obj ('CL_AZS', 'TABLE');
exec  FRAMEWORK.pkg_utl_drop.proc_drop_obj ('CL_CUSTOMER', 'TABLE');
exec  FRAMEWORK.pkg_utl_drop.proc_drop_obj ('CL_FUEL_TYPE', 'TABLE');
exec  FRAMEWORK.pkg_utl_drop.proc_drop_obj ('CL_PAYMENT_TYPE', 'TABLE');
exec  FRAMEWORK.pkg_utl_drop.proc_drop_obj ('CL_PAYMENT', 'TABLE');

CREATE TABLE CL_PAYMENT 
   (	ID_PAYMENT NUMBER(16,0) not null, 
	ID_CUSTOMER NUMBER(10,0) not null, 
	ID_PAYMENT_TYPE NUMBER(2,0) not null, 
	ID_STATION NUMBER(4,0) not null, 
	ID_FUEL_TYPE NUMBER(3,0) not null, 
	PAYMENT_DATE DATE NOT NULL,  
	PRICE NUMBER(8,2) not null, 
	QUANTITY NUMBER(10,3) not null, 
	PAYMENT_TIME VARCHAR2(10 BYTE) not null, 
	INSERT_DATE DATE
   )PARTITION BY RANGE (PAYMENT_DATE)
  (
  PARTITION pr0 VALUES LESS THAN (TO_DATE('01-01-2016', 'DD-MM-YYYY')),
  PARTITION pr1 VALUES LESS THAN (TO_DATE('01-01-2017', 'DD-MM-YYYY')),
  PARTITION pr2 VALUES LESS THAN (TO_DATE('01-01-2018', 'DD-MM-YYYY')),
  PARTITION pr3 VALUES LESS THAN (TO_DATE('01-01-2019', 'DD-MM-YYYY')),
  PARTITION pr4 VALUES LESS THAN (MAXVALUE)
  );

CREATE TABLE CL_AZS 
   (	ID3NF NUMBER(10,0) not null, 
	NO NUMBER(4,0) not null, 
	LOCATION_DESC VARCHAR2(255 BYTE) not null, 
	LATITUDE NUMBER(10,6) not null, 
	LONGITUDE VARCHAR2(26 BYTE) not null, 
	ROAD1 VARCHAR2(26 BYTE) not null, 
	ROAD2 VARCHAR2(5 BYTE) not null, 
	DT NUMBER(1,0) not null, 
	DT2 NUMBER(1,0) not null, 
	AI92 NUMBER(1,0) not null, 
	BN92 NUMBER(1,0) not null, 
	AI95 NUMBER(1,0) not null, 
	LPG NUMBER(1,0) not null, 
	AI98 NUMBER(1,0) not null, 
	ID_COUNTRY NUMBER(10,0) not null, 
	COUNTRY_NAME VARCHAR2(100 BYTE) not null, 
	COUNTRY_CODE VARCHAR2(100 BYTE) not null, 
	ID_PARENT NUMBER(10,0) not null, 
	ID_REGION NUMBER(10,0) not null, 
	REGION_NAME VARCHAR2(100 BYTE) not null, 
	ID_DISTRICT NUMBER(10,0) not null, 
	DISTRICT_NAME VARCHAR2(100 BYTE) not null, 
	UPDATE_DATE DATE, 
	INSERT_DATE DATE
   );
  CREATE TABLE CL_CUSTOMER 
   (	--CUSTOMER_SURR_ID NUMBER NOT NULL,  
	ID3NF NUMBER(10,0) not null, 
	CUSTOMER_NK VARCHAR2(50 BYTE) not null, 
	ID_CUSTOMER_TYPE NUMBER(1,0) not null, 
	CUSTOMER_TYPE_DESCRIPTION VARCHAR2(50 BYTE) not null, 
	ID_LOCATION NUMBER(10,0) not null, 
	ADDRESS VARCHAR2(50 BYTE) not null, 
	PHONE VARCHAR2(50 BYTE) not null, 
	POSTALCODE NUMBER(8,0) not null, 
	EMAIL VARCHAR2(50 BYTE) not null, 
	FIRST_NAME VARCHAR2(50 BYTE) not null, 
	LAST_NAME VARCHAR2(50 BYTE) not null, 
	MIDDLE_NAME VARCHAR2(50 BYTE) not null, 
	BIRTHDAY DATE NOT NULL,  
	SEX NUMBER NOT NULL,  
	VEHICLE_DESC VARCHAR2(50 BYTE) not null, 
	VEHICLE_YEAR NUMBER NOT NULL,  
	TAX_ID VARCHAR2(50 BYTE) not null, 
	RUS_FULL_NAME VARCHAR2(400 BYTE) not null, 
	MNS_NAME VARCHAR2(128 BYTE) not null, 
	MNS_NUM NUMBER NOT NULL,  
	UPDATE_DATE DATE NOT NULL,  
	INSERT_DATE DATE
)   
;

  CREATE TABLE CL_PAYMENT_TYPE 
   (	--PAYMENT_TYPE_SURR_ID NUMBER NOT NULL,  
	ID3NF NUMBER(16,0) not null, 
	ID_PAYMENT_TYPE NUMBER(2,0) not null, 
	ENG_TYPE VARCHAR2(10 BYTE) not null, 
	RUS_TYPE VARCHAR2(100 BYTE) not null, 
	DESCRIPTION VARCHAR2(128 BYTE) not null, 
	START_DATE DATE NOT NULL,  
	END_DATE DATE NOT NULL,  
	IS_ACTIVE NUMBER NOT NULL,  
	INSERT_DATE DATE
   )
;

  CREATE TABLE CL_FUEL_TYPE 
   (	--FUEL_TYPE_SURR_ID NUMBER NOT NULL,  
	ID3NF NUMBER(16,0) not null, 
	ID_FUEL_CODE NUMBER(3,0) not null, 
	ENG_TYPE VARCHAR2(10 BYTE) not null, 
	RUS_TYPE VARCHAR2(26 BYTE) not null, 
	DESCRIPTION VARCHAR2(128 BYTE) not null, 
	START_DATE DATE NOT NULL,  
	END_DATE DATE NOT NULL,  
	IS_ACTIVE NUMBER NOT NULL,  
	INSERT_DATE DATE
   );
