CREATE TABLE wrk_employees
  (
    "FULL_NAME"   NUMBER(10,0),
    "LAST_NAME"   VARCHAR2(200 BYTE),
    "FIRST_NAME"  VARCHAR2(50 BYTE),
    "MIDDLE_NAME" VARCHAR2(50 BYTE),
    "EMAIL"       VARCHAR2(50 BYTE)
  ) ;