  CREATE TABLE wrk_provider_information 
   (	"PROVIDER_CODE" NUMBER(10,0), 
	"PROVIDER_NAME" VARCHAR2(200 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"ZIP_CODE" VARCHAR2(50 BYTE), 
	"ADDRESS" VARCHAR2(50 BYTE), 
	"CITY" VARCHAR2(50 BYTE)
   ) ;