CREATE TABLE wrk_product_hierarchy
  (
    "PRODUCT_NAME"     VARCHAR2(200 BYTE),
    "CATEGORY_NAME"    VARCHAR2(200 BYTE),
    "CATEGORY_CODE"    VARCHAR2(50 BYTE),
    "SUBCATEGORY_NAME" NUMBER(10,0),
    "SUBCATEGORY_CODE" VARCHAR2(200 BYTE)
  ) ;