SELECT CASE 
          WHEN GROUPING_ID (TIMES.CALENDAR_MONTH_DESC,CHANNELS.CHANNEL_DESC,COUNTRIES.COUNTRY_NAME) = 7
          THEN 'GRAND TOTAL'
          ELSE TIMES.CALENDAR_MONTH_DESC 
END YEAR_MONTH,
       CASE  
         WHEN GROUPING_ID (TIMES.CALENDAR_MONTH_DESC,CHANNELS.CHANNEL_DESC,COUNTRIES.COUNTRY_NAME) = 3
          THEN 'Total by Channels'
          ELSE CHANNELS.CHANNEL_DESC
          END CHANNEL,
       CASE 
          WHEN  GROUPING_ID (TIMES.CALENDAR_MONTH_DESC,CHANNELS.CHANNEL_DESC,COUNTRIES.COUNTRY_NAME) = 1
          THEN CHANNELS.CHANNEL_DESC || ' Total by Sales'
          ELSE COUNTRIES.COUNTRY_NAME
          END  COUNTRY,
       TO_CHAR(MAX(AMOUNT_SOLD),'9,999') "MAX_SALES$",
       TO_CHAR(MIN(AMOUNT_SOLD),'9,999') "MIN_SALES$",
       TO_CHAR(SUM(AMOUNT_SOLD),'9,999,999') "SALES$"
FROM TIMES, SALES, CHANNELS, COUNTRIES, CUSTOMERS
WHERE SALES.TIME_ID=TIMES.TIME_ID and SALES.CUST_ID=CUSTOMERS.CUST_ID and
      SALES.CHANNEL_ID=CHANNELS.CHANNEL_ID and TIMES.CALENDAR_MONTH_DESC='2000-12' and
      CHANNELS.CHANNEL_DESC in ('Internet', 'Direct Sales') and CUSTOMERS.COUNTRY_ID=COUNTRIES.COUNTRY_ID
GROUP BY ROLLUP (TIMES.CALENDAR_MONTH_DESC, CHANNELS.CHANNEL_DESC,  COUNTRIES.COUNTRY_NAME);
