--PARALLEL DML.
EXPLAIN PLAN FOR
UPDATE /*+ PARALLEL(CUST) */ SH.CUSTOMERS CUST
SET CUST.CUST_INCOME_LEVEL = 'HIGH' 
WHERE CUST_INCOME_LEVEL = 'L: 300,000 and above' ;
  
SELECT * FROM TABLE (dbms_xplan.display);
