CREATE TABLE ce_sales
  (
    Sales_id            NUMBER(8) PRIMARY KEY,
    Event_DT            DATE NOT NULL,
    Customer_code       VARCHAR2(8) NOT NULL,
    Employee_code       VARCHAR2(8) NOT NULL,
    Store_code          VARCHAR2(8) NOT NULL,
    Book_id             NUMBER(8) NOT NULL,
    Payment_id          NUMBER(8) NOT NULL,
    Check_id            VARCHAR2(8) NOT NULL,
    Quantity            NUMBER(5) NOT NULL,
    Discount            NUMBER(2,3) NOT NULL,
    Unit_price_BYN      NUMBER(10,2) NOT NULL,
    Unit_price_disc_BYN NUMBER(10,2) NOT NULL,
    Sales_Amount_BYN    NUMBER(10,2) NOT NULL,
    BYN_USD             NUMBER(8,3) NOT NULL,
    Unit_price_USD      NUMBER(10,2) NOT NULL,
    Unit_price_disc_USD NUMBER(10,2) NOT NULL,
    Sales_Amount_USD    NUMBER(10,2) NOT NULL,
    Insert_DT           DATE NOT NULL,
    Update_DT           DATE NOT NULL,
    CONSTRAINT fk_date FOREIGN KEY (Event_DT) REFERENCES dim_time_day(full_date_dt),
    CONSTRAINT fk_customer FOREIGN KEY (customer_code) REFERENCES ce_customers(customer_code),
    CONSTRAINT fk_employee FOREIGN KEY (employee_code) REFERENCES ce_employees(employee_code),
    CONSTRAINT fk_store FOREIGN KEY (store_code) REFERENCES ce_stores(store_code),
    CONSTRAINT fk_product FOREIGN KEY (book_id) REFERENCES ce_all_books(book_id),
    CONSTRAINT fk_payment FOREIGN KEY (payment_id) REFERENCES ce_payments(payment_id)
  );
