/************NOTE**************/
/*IN THE BATCH FILE 2 COMMANDS ARE COMMENTTED:
CREATE DIRECTORY
AND
DROP TABLESPACES
ALSO IN THE FOLDER SCRIPT THAT DELETE EVERYTHING 
FROM THE SCHEMA WHERE IT'S RUN
*/

@D:\MIF\batch;